### ISSUE TITLE
Request: simple labels on http://geojson.io/

### ISSUE THREAD

**Issue by maphew** [mapbox/geojson.io#287]
It would be really, really nice if an attribute column could be used for labels, especially for point data. 

The resulting labels wouldn't have to be fancy, with leader lines and automatic no-overlap logic etc. (thought that would be nice), just simple points with a name beside would go a long way to making a better and more useful 
map.

![geojson io_ edit geojson_2013-11-22_15-41-28](https://f.cloud.github.com/assets/486200/1605147/86f0738e-53d0-11e3-9975-20459bb18aa2.png)

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would completed this task but it is not one of my own priorities to implement it myself.

**Comment by MartinThoma** [comment]
It would be nice if we could have a `label` attribute for areas, which is shown at the representative point of the area (e.g. https://shapely.readthedocs.io/en/stable/manual.html#object.representative_point )
