### ISSUE TITLE
Issue: LatLng objects inverted

### ISSUE THREAD

**Issue by padillla** [mapbox/geojson.io#289]
EDIT: this follows GeoJson spec correctly.

I make a marker, it seems to be inverted:

![latlng](https://f.cloud.github.com/assets/2403209/1658069/7c609560-5b8d-11e3-80a4-ec964e4d694e.JPG)

This is the point I want:

![latlng2](https://f.cloud.github.com/assets/2403209/1658137/58704c94-5b8e-11e3-92f6-38723a84199b.JPG)

When I use it on google maps it points where I want:

![latlnggmaps](https://f.cloud.github.com/assets/2403209/1658169/d4bbc5bc-5b8e-11e3-8bab-c4f224db300b.JPG)

 Leaflet loads the inverted point(Antartica instead of Costa Rica).

I had to invert all latlngs created in geojson.io to get it to work properly on Leaflet.

Is this a real issue or am I doing something wrong?

**Comment by rulight** [comment]
To solve this you can just invert the coordinates manually with js:
  var latlngNew = $.extend(true, {}, latlng); // copy the object with jquery to a new one
			   	latlngNew.lat = latlng.lng; 
			   	latlngNew.lng = latlng.lat;
			    return L.marker(latlngNew, {icon: myIcon});
