### ISSUE TITLE
Renamed Gist results in extra map.geojson file in same Gist

### ISSUE THREAD

**Issue by rcheetham** [mapbox/geojson.io#292]
I did a round-trip in which I created a geojson Gist in geojson.io, then re-named it in GitHub and edited it, then loaded it to geojson.io and made some more edits and saved.  This series of events all worked flawlessly until the last step.  The outcome was that a new map.geojson file was saved to the Gist, rather than an edit to the original file.

So here's the sequence of events I used to reproduce it:
- Create a map - put some stuff on it - maybe assign an attribute or two
- Save - creates a Gist with file name "map.geojson"
- Edit in GitHub - specifically change the file name - perhaps to "map2.geojson"
- Open in geojson.io - the new file name (map2.geojson) will be displayed and it will load properly
- Make some edits in geojson.io
- Save - appears to save ok, but creates a new map.geojson file in the same Gist, rather than editing the original map (map2.geojson) - now there will be two geojson files in the same Gist.

**Comment by tmcw** [comment]
Closing, unless someone wants to take on this issue, the map.geojson assumption is simple and efficient.
