### ISSUE TITLE
Authentication with GitHub failed

### ISSUE THREAD

**Issue by AlexxHansson** [mapbox/geojson.io#309]
GET https://geojsonioauth.herokuapp.com/authenticate/d629218879edf000e3b1  lib.js:2716
xhr.send lib.js:2716
xhr.(anonymous function) lib.js:2702
module.exports site.js:18818
geojsonIO site.js:18855
require../core/api site.js:18836
s site.js:1
e site.js:1
(anonymous function) site.js:1

**Comment by cyrilchapon** [comment]
Confirmed same problem chrome @ mac
