### ISSUE TITLE
Not obvious how to save to Github

### ISSUE THREAD

**Issue by konklone** [mapbox/geojson.io#321]
It's obvious how to save to a Gist - `Save` does that by default. How do I save to a file in a proper Github repo?

**Comment by wuhland** [comment]
I agree with @konklone and think being able to save direct to Github while tracking changesets would be really useful for collaborative mapping. Trying to get a sense for what LOE would be if at all possible.

**Comment by chriswhong** [comment]
saving to github is being removed, closing as no longer relevant
