### ISSUE TITLE
Edit single geojson feature

### ISSUE THREAD

**Issue by landonreed** [mapbox/geojson.io#327]
Some geojson feature collections are really large files with lots of features.  Editing the shapes for these large files is currently impossible in geojson.io, because clicking "Edit layers" makes the entire feature collection editable (bogging down and crashing your browser).

Feature request: enable selective editing so that large files can be edited feature by feature rather than all at once.

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would completed this task but it is not one of my own priorities to implement it myself.
