### ISSUE TITLE
Error saving to/accessing GitHub tree

### ISSUE THREAD

**Issue by landonreed** [mapbox/geojson.io#338]
The new interface looks great!

Unfortunately, I'm getting an error when the GitHub tree is accessed (see image).  I tried logging out, using an incognito window, revoking access token... but nothing seemed to fix the bug.  Same experience on Firefox and Chrome.

Any idea what's going on?  The error is being thrown [here](https://github.com/mapbox/geojson.io/blob/gh-pages/dist/site.js#L4919).

![image](https://cloud.githubusercontent.com/assets/2370911/2668969/d34f0cae-c0bd-11e3-89e8-16798c5dcd72.png)

**Comment by ustroetz** [comment]
I am still getting an error when I try to save a opened file from Github. Though my error looks differrent
![screen shot 2015-03-04 at 14 26 12](https://cloud.githubusercontent.com/assets/4493762/6484247/81218078-c27a-11e4-8663-eaf517fc5d14.png)
