### ISSUE TITLE
Multipolygon Edit Layers JS Error

### ISSUE THREAD

**Issue by Jesmaster** [mapbox/geojson.io#345]
Steps to reproduce

Paste the following json: 
{"type":"MultiPolygon","coordinates":[[[[-73.98532390594499,40.747679624003],[-73.98532390594499,40.747679624003],[-73.98532390594499,40.747679624003],[-73.98532390594499,40.747679624003]]],[[[-73.98532390594499,40.747695880149],[-73.988435268402,40.743371605179],[-73.98910045623801,40.742396165946],[-73.989014625549,40.741567031351],[-73.99036645889301,40.737096029431],[-73.991804122925,40.735209989416],[-73.992104530334,40.735372581178],[-74.006888866425,40.741713349971],[-74.008004665375,40.740331439051],[-74.008541107178,40.733388934529],[-74.004592895508,40.734006798024],[-74.002361297607,40.734348246441],[-74.002779722214,40.73354340094],[-74.001148939133,40.731746690505],[-73.994228839874,40.728388907014],[-74.014506340027,40.704651945645],[-74.014313220978,40.704424211989],[-74.01444196701,40.703139128909],[-74.01403427124001,40.702488444476],[-74.01296138763399,40.702407108475],[-74.011158943176,40.703106594838],[-74.010043144226,40.70343193483],[-74.0074467659,40.70510741062],[-74.006309509277,40.704229011093],[-74.003112316132,40.706327390743],[-74.00015115737899,40.707937730287],[-73.99884223938,40.708637158566],[-73.996889591217,40.709190189678],[-73.99176120758101,40.709905870183],[-73.99261951446501,40.71455760597],[-73.990302085876,40.719176490551],[-73.993928432465,40.720363687279],[-73.992555141449,40.72416907928],[-73.986225128174,40.722233885749],[-73.980388641357,40.730478395104],[-73.98991584777799,40.73449458094],[-73.989958763123,40.735340062858],[-73.985409736633,40.741453227756],[-73.98708343505901,40.742136046401],[-73.98298501968399,40.747777160821],[-73.98472309112501,40.748411146652],[-73.98532390594499,40.747695880149]]]]}

Click the Edit layers button

Nothing happens and you will see a javascript error in the console.
"Uncaught TypeError: undefined is not a function"

**Comment by tmcw** [comment]
Closing; Leaflet.draw issue is 3 years old. Not holding breath.
