### ISSUE TITLE
Crash on gist files > 1 MB

### ISSUE THREAD

**Issue by jwass** [mapbox/geojson.io#364]
The Gist API now just truncates file contents to 1 MB. https://developer.github.com/changes/2014-05-06-gist-api-now-truncating-large-files/

When truncated, the contents will not be valid JSON or GeoJSON. It will throw a SyntaxError on JSON.parse(). See http://geojson.io/#id=gist:/a0d1577b24482c3bdf95 for an example of this in action.

The gist response's file entry has a `truncated` flag to indicate if the data is chopped. So I think the fix is to check if the data is truncated and then make a second request to the `raw_url` field to grab the full contents.

This also breaks most uses of anonymous gist upload for [geojsonio-cli](https://github.com/mapbox/geojsonio-cli) and [geojsonio.py](https://github.com/jwass/geojsonio.py) for now until fixed.

**Comment by geocentrum1** [comment]
Hi guys, any successful example which can load GEOJSON > 1MB from Gist? Unfortunatelly for me it doesnt work :-( GEOJSON layer: https://gist.github.com/geocentrum1/6162cda1f4102b232511
