### ISSUE TITLE
Issue with 'Save Shapefile' output 

### ISSUE THREAD

**Issue by alexkapps** [mapbox/geojson.io#365]
First, awesome tool!

I downloaded a polygon shapefile with the 'Save Shapefile' functionality and, when attempting to 'Save As..' to a new projection in QGIS, QGIS would crash. To get around this I instead downloaded the KML and saved it as a shapefile. Would this be a problem with the shapefile generated? I do not think it is a bug in my QGIS as I have not had this problem with shapefiles of alternative origins.

**Comment by MappingKat** [comment]
I also get some strange shapefile errors.  For some reason shapefile exports from geojson does not work in a platform I am working on, but when I open it up in QGIS and save it as a shapefile it works fine.  Let me investigate this more when I get some time... I'll open up and compare the two files...
