### ISSUE TITLE
How to change GitHub OAuth callback?

### ISSUE THREAD

**Issue by odessky** [mapbox/geojson.io#366]
_Port 8080 is recommended because by default geojson.io will use a prose/gatekeeper auth server that redirects back to http://localhost:8080/ for GitHub OAuth._

I want change callback url to http://mydomain.com/map/

**Comment by rostanetek** [comment]
I set-up the Heroku, I made changes in src/config.js (and dist.site.js) and uploaded on the webhosting. When i click on "login", GitHub asks me for Authentisation, but then there is still error "Authentication with GitHub failed". Any idea what is wrong?

**Comment by geocentrum1** [comment]
Finnally I got it! There are some crucial steps: first of all it work on port 8080 only (e.g. on 8888 it didnt work). 2) On GIThub register OAuth (in applications->developer options), which return ID + secret key. 3) On Heroku register new application 3) Edit src/config.js + dist.site.js...finnally it works like a charm!
