### ISSUE TITLE
Invalid geojson silently fails if on one line

### ISSUE THREAD

**Issue by springmeyer** [mapbox/geojson.io#368]
If `{ "type":"FeatureCollection", "features": [ { "type":"Feature", "geometry": { "type":"LineString","coordinates":[[0,0],[10,10]] } } ]}` is put into geojson.io it quietly renders nothing. It is invalid due to the missing `properties` however this only becomes apparent when a line break is added.

**Comment by chriswhong** [comment]
This is fixed in https://github.com/mapbox/geojson.io/pull/703
