### ISSUE TITLE
GitHub and Gist files do not load from file browser (must reload page)

### ISSUE THREAD

**Issue by landonreed** [mapbox/geojson.io#385]
When selecting a gist or GitHub file from the geojson.io file browser, you must reload the page in order for the data to load.  I'm not entirely sure what the source of this error is, but does it have something to do with [`d.content` in `data.parse()`](https://github.com/mapbox/geojson.io/blob/gh-pages/src/core/data.js#L213) being undefined?

I'm getting this behavior in multiple browsers on OS X.

**Comment by vappiah** [comment]
Just had the same issue
