### ISSUE TITLE
Nothing happens on open from github

### ISSUE THREAD

**Issue by reyemtm** [mapbox/geojson.io#394]
Maybe I am confused on how this is supposed to work, but when I click open, github, navigate to the file, it shows up to the right of the menu, but is not loaded in the json editor window and does not show up on the map. I can copy/paste the same file into the editor window, edit it and save it back to github without issues. I am looking for a way to host and edit simple map files, and have multiple contributors, and this seems like a cool way to do that, too bad it does not work.

**Comment by landonreed** [comment]
This actually may have been due to a bug introduced in a recent commit.  For some reason the fileUrl for GitHub files from repos was incorrectly modified: https://github.com/mapbox/geojson.io/blob/gh-pages/src/source/github.js#L117-L130

**Comment by camilleanne** [comment]
Should be fixed by https://github.com/mapbox/geojson.io/pull/401
