### ISSUE TITLE
white blank screen after saving

### ISSUE THREAD

**Issue by zjmu916** [mapbox/geojson.io#396]
After saving and get a url from share, it shows up with white blank screen now.

**Comment by camilleanne** [comment]
Should be fixed by https://github.com/mapbox/geojson.io/pull/401

**Comment by zjmu916** [comment]
it seems still not working?!

**Comment by camilleanne** [comment]
Hm, maybe it is a different issue that the one I was encountering. Are there any errors in your developer tools console?

**Comment by camilleanne** [comment]
Reopening. Sharing on bl.ocks is broken because mapbox.js files are now local.

**Comment by zjmu916** [comment]
Is that meaning Sharing no longer to be used with map box?

**Comment by camilleanne** [comment]
No, it's a temporary problem. I will have it fixed today.
