### ISSUE TITLE
Update mapbox.js to 2.1.4 on shared maps

### ISSUE THREAD

**Issue by camilleanne** [mapbox/geojson.io#403]
Geojson.io is mostly updated to Mapbox.js 2.1.4 with the exception of [share.html](https://github.com/mapbox/geojson.io/blob/gh-pages/data/share.html#L32-L34). This should be updated at some point from 1.6.2, `detectRetina: true` removed, and `access_token` from [config.js](https://github.com/mapbox/geojson.io/blob/gh-pages/src/config.js#L3) added.

**Comment by tmcw** [comment]
This is now updated to 2.2.2!
