### ISSUE TITLE
Autologin?

### ISSUE THREAD

**Issue by rostanetek** [mapbox/geojson.io#404]
In case of localhost - is there any possibility to set login and password into the source code, so user will be logged into Github initially by default?

**Comment by tmcw** [comment]
This would be a significant amount of code to change, but it would likely amount to gutting the user auth routine and [hardcoding a token](https://github.com/mapbox/geojson.io/blob/3ae772e4cd990cff8e337cf3c39b04d755dd561a/src/core/user.js#L41) here.

**Comment by tmcw** [comment]
Closing: this falls outside of the scope of geojson.io and isn't something that I can help much with, remotely.
