### ISSUE TITLE
Edit multiple points in one go?

### ISSUE THREAD

**Issue by tannerlinsley** [mapbox/geojson.io#407]
This would be a great feature. I have a ton of geoJSON that is slightly skewed from GPS inaccuracies.  This would be so much easier than using qgis ;)

**Comment by tmcw** [comment]
Can you be more specific about what you're asking? It's already possible to edit multiple points in one go by clicking the "Edit" button 
![2015-01-29 at 10 58 am](https://cloud.githubusercontent.com/assets/32314/5960760/b4be6364-a7a5-11e4-8912-f76f30462a86.png)

**Comment by tannerlinsley** [comment]
Yeah.  What I'm referring to is selecting multiple points with a selection box (or shift and ctrl, much like file selection on your computer) and dragging them all together.  This way you would not have to click and drag individual points one at a time to move an entire route or group of markers.

**Comment by tmcw** [comment]
Okay, that'd be a feature upstream in [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw).

**Comment by tmcw** [comment]
This would be upstream in [Leaflet.draw](https://github.com/leaflet/leaflet.draw) - closing here, feel free to re-file there.
