### ISSUE TITLE
Shared link can't be opened 

### ISSUE THREAD

**Issue by zjmu916** [mapbox/geojson.io#408]
http://bl.ocks.org/anonymous/raw/f7410524434d66d0ead0/

The link above with no problem can be opened in pc.
Tried a couple of times, it can not be opened at iphone when use safari or google chrome. why?

**Comment by zjmu916** [comment]
The real issue is not relationg to open share link in smartphone, but with white blank screen and only zooming tab on the left top when I open is in pc.

**Comment by camilleanne** [comment]
@zjmu916 I opened this link in Safari and Chrome on iPhone, as well as on a couple different versions of IE down to IE 8 and everything was fine.

I'm going to assume that this had to do with https://github.com/mapbox/geojson.io/pull/402 and the issue is now resolved.
