### ISSUE TITLE
Invalid GeoJSON when using NULL as ID

### ISSUE THREAD

**Issue by iH8** [mapbox/geojson.io#412]
Update: never mind, party on. I wasn't paying attention, this issue's origin is mapbox/geojsonhint, filed it there. Excuse me, close please.

This is not according to specification. The only thing that is stated in the spec. about the identifier is the following:

>If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id".

http://geojson.org/geojson-spec.html#feature-objects

Since nothing else is mentioned about the type of ID, it should adhere to the JSON spec where the property of an object can be any of the following: String, Number, null, true, false, Array or Object

**Comment by tmcw** [comment]
Yep, resolved over at the geojsonhint repo. Non-number-string-undefined ids are valid in GeoJSON 1.0 but soon will be invalid in draft-geojson, and so we validate for the future.
