### ISSUE TITLE
setting up geojson.io with a different gatekeeper

### ISSUE THREAD

**Issue by rostanetek** [mapbox/geojson.io#420]
Based on https://github.com/mapbox/geojson.io/issues/366 I set-up the Heroku, I made changes in src/config.js (and what about dist.site.js?) and uploaded it on my webhosting (http://rostanetek.cz/1/). When i click on "login", GitHub asks me for authentification, but then there is still error "Authentication with GitHub failed". But when I went to github manually (in new tab/window) I am logged in. Any idea what is wrong?

**Comment by tmcw** [comment]
Really any number of things could be wrong: you might have configured the callback URL correctly, or entered the wrong secret and access tokens into your gatekeeper or geojson.io implementations.

**Comment by bmcbride** [comment]
@rostanetek, make sure you rebuild by running `make` after modifying config.js. See https://github.com/mapbox/geojson.io#development.

**Comment by rostanetek** [comment]
I am almost sure that IDs and tokens are right. Are there any step-by-step instructions? Or anyone who successfully implement it on own server?

**Comment by mikemorris** [comment]
@rostanetek Prose also uses gatekeeper for GitHub authentication, you may find this thread helpful https://github.com/prose/prose/issues/707

**Comment by tmcw** [comment]
Closing: this is a support request, and not something I can debug much remotely.
