### ISSUE TITLE
Scrolling of datalist for icon markers

### ISSUE THREAD

**Issue by colemanm** [mapbox/geojson.io#421]
The list of icon types isn't scrollable, so you can't pick easily from all of the available icons. Using the arrow keys to move down in the list works, though. This is in Chrome 40.0.2214.111:

![icon list](https://cldup.com/3CZ9fKUJci.gif)

**Comment by samanpwbb** [comment]
It's [impossible to style datalists](http://webdesign.tutsplus.com/tutorials/introducing-the-html5-datalist-element--webdesign-9888) :cry:

**Comment by chriswhong** [comment]
simplestyle functionality is being removed, closing as no longer relevant
