### ISSUE TITLE
Save to Github always writes to top-level directory

### ISSUE THREAD

**Issue by probins** [mapbox/geojson.io#423]
When I save to Github, I'm presented with a dialogue that enables me to select where in the directory hierarchy I want to save, but ... it always saves to the top-level regardless of what I select. Example: I have 2 directories in the repo, `lib` and `data`; I select `data`, but it writes to the top-level dir instead. Because this is a git commit, it's a pain to rectify, as I have to revert the commit and resubmit; as this is more trouble than it's worth, it makes geojson.io less useful than it might be.

**Comment by vietnugent** [comment]
I'm experiencing the same issue
