### ISSUE TITLE
"Save KML" generates invalid KML 2.2 if user columns exist

### ISSUE THREAD

**Issue by sfkeller** [mapbox/geojson.io#428]
If user columns exist and when doing a "Save KML" this generates an invalid KML 2.2. 

Wrong example:
```xml
  <kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Placemark>
      <Polygon>...</Polygon>
      <ExtendedData>...</ExtendedData>
    </Placemark>
  </Document>
  </kml>
```

Correct example:
```xml
  <kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Placemark>
      <ExtendedData>...</ExtendedData>
      <Polygon>...</Polygon>
    </Placemark>
  </Document>
  </kml>
```

Test with any KML file with www.kmlvalidator.org/ exported by this nice tool geojson.io.

**Comment by tmcw** [comment]
KML restricts the ordering of elements? I don't see anything about this on https://developers.google.com/kml/documentation/kmlreference

**Comment by sfkeller** [comment]
It seems so. At least the KMLvalidator and another KML parser report 
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'ExtendedData'. 
One of '{"http://www.opengis.net/kml/2.2":PlacemarkSimpleExtensionGroup, 
"http://www.opengis.net/kml/2.2":PlacemarkObjectExtensionGroup}' is expected.
```

**Comment by sfkeller** [comment]
... and to me even the KML documenation you mentioned implies that tag <Geometry> is specific to tag <Placemark> and therefore follows inherited tags like optional tags <ExtendedData>: See https://developers.google.com/kml/documentation/kmlreference#placemark 

BTW: I'd prefer GeoPackage over KML and Shapefiles anway (c.f. issue #429 ) :-) .

**Comment by tmcw** [comment]
Ah, indeed it's a sequence in the xsd file. Should be a simple fix in tokml.
