### ISSUE TITLE
New feature request: Save GeoPackage...

### ISSUE THREAD

**Issue by sfkeller** [mapbox/geojson.io#429]
I propose "Save GeoPackage..." (vector, version 1.0) as a new feature in the Save menu.

I'm a promotor of GeoPackage as "the better alternative" to Shapefiles. As James said, Shapefiles belong to grandfathers memories... This would also be another contribution of this nice tool geojson.io to interoperability and OGC compliance: See also http://lists.osgeo.org/pipermail/discuss/2015-March/013992.html .

**Comment by tmcw** [comment]
Patches accepted, otherwise a strong no. I was on the committee that created GeoPackage and have negative opinions of its specification, architecture, process, and nearly everything else.

**Comment by sfkeller** [comment]
Thanks for you openess to accept such a patch. After August 2015 I'll probably have more resources but don't mind if anybody steps in.

I'm no insider to OGR and have had my issues too. But to me, interoperability stands above all. And like Shapefile, GeoJSON has it's limits too (e.g. no CRS). So let us stand together and don't let proprietary formats profit from this Babylonian situation in GIS.

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would completed this task but it is not one of my own priorities to implement it myself.
