### ISSUE TITLE
UI does not load after clicking Open > Gist 

### ISSUE THREAD

**Issue by nicolas-raoul** [mapbox/geojson.io#431]
It is stuck like this:

![geojson-bug](https://cloud.githubusercontent.com/assets/99590/6682514/6c450a42-ccbd-11e4-892b-959af713cdb5.png)

After a minute I tried clicking "load more", but it does not do anything.

Ubuntu 2014.04 Firefox 36.0.1

**Comment by tmcw** [comment]
Closing; please re-file with more details.
