### ISSUE TITLE
run geojsonhint on togeojson'ed inputs

### ISSUE THREAD

**Issue by nicolas-raoul** [mapbox/geojson.io#432]
I opened [this KML file](https://github.com/wikivoyage/maps/blob/master/coordinates-but-no-image.kml?raw=true) in geojson.io

Problem: Nothing is shown on the map.

The places names appear in "Table" though.

**Comment by tmcw** [comment]
This is invalid input: there are lines like

```xml
<Placemark><name>Don Franco's</name><Point><coordinates>,15.66388</coordinates></Point></Placemark>
```

In which there is only one coordinate: coordinates need to be both longitude and latitude.
