### ISSUE TITLE
Unable to define projection

### ISSUE THREAD

**Issue by Chaz6** [mapbox/geojson.io#433]
My data uses OSGB1936 however the app assumes all data is projected using WGS1984. It should be possible to specify the projection to be used.

**Comment by Chaz6** [comment]
I tried adding a coordinate reference system as per the GeoJSON spec but this did not help.

"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::27700" } }

**Comment by tmcw** [comment]
geojson.io doesn't support alternative projections - you'll need to reproject your data to EPSG:4326 before import.

**Comment by gipong** [comment]
Hi, if your geospatial data in a GIS software format(.shp), i make a pure javascript lib to convert zip file with shp, dbf, prj to geojson and reproject the data with correct encoding in JavaScript. it also support non-english encoding to correctly show in geojson. You may give it a try :)
https://github.com/gipong/shp2geojson.js

**Comment by tmcw** [comment]
Closing: feel free to use any script to reproject data before dropping into geojson.io, but data projects are one thing that geojson.io does not plan on doing.
