### ISSUE TITLE
Marker attributes with double quotes are not written

### ISSUE THREAD

**Issue by fnicollet** [mapbox/geojson.io#437]
Hello

I placed a marker on the map, added a row "description", for which the value is:
"Ensemble pour la paix et la Justice" G7 - 1996 Lyon
(with double quotes)

Press Save, open the pop-up and the value is gone. It works if I remove the double quotes, probably an escaping issue somewhere

Fabien

**Comment by tmcw** [comment]
I can't replicate this issue - double quotes are preserved in all cases. Was probably fixed sometime between 2015 and now.

**Comment by fnicollet** [comment]
Thanks, looks like they are properly escaped now, yes
