### ISSUE TITLE
Python - I created a json file from parsed html data, I cannot map my json file  at geojson.io--help--

### ISSUE THREAD

**Issue by deb133** [mapbox/geojson.io#439]
I get the following error:
Invalid JSON file: SyntaxError: Unexpected token (

Here is my code - where I write the json file in unicode- or should it not be in unicode?

from bs4 import BeautifulSoup
import urllib2, sys, io, json, requests

def get_data(**kwargs):
    """parse and save the data"""
    try:
        with io.open('AIS_Page.txt', 'w', encoding = 'utf-8') as AIS:
            url = 'http://www.sailwx.info/shiptrack/shipposition.phtml?call=wrn5495'
            web = BeautifulSoup(urllib2.urlopen(url).read())
            for tr in web.find_all ('tr')[4:]:
                tds = tr.find_all('td')
                lat=  tds[0].string, tds[1].string
                AIS.write(unicode(lat))
    except IndexError:
        return None

if __name__ == '__main__':
    get_data()
    print 'saved'

output of the file looks something like the following:
(u'2015-Apr-27 22:38', u"N\xa047\xb039' W\xa0122\xb019'")

**Comment by sgillies** [comment]
Geojson.io requires JSON data formatted as [GeoJSON](http://geojson.org). Your script does not write GeoJSON or any other kind of JSON. Please see the examples at http://geojson.org.

This is not a problem with geojson.io.

**Comment by deb133** [comment]
Hi Sean,

I am just having such difficulty converting the whole csv file to *.json
(to map in geojson.io).

I have attached my 'barebones' code- if you can please help me that would
be greatly appreciated.

Thank you!
Darcy

Darcy Balcarce
darcy.e.balcarce@gmail.com
