### ISSUE TITLE
unclosed polygons in shapefile

### ISSUE THREAD

**Issue by anneb** [mapbox/geojson.io#442]
Save as shapefile does not close 1st and 2nd polygons of following geojson:

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              4.919147193431854,
              52.369374822056535
            ],
            [
              4.919192790985107,
              52.36942231453366
            ],
            [
              4.919396638870239,
              52.36935189463551
            ],
            [
              4.919348359107971,
              52.36930112673232
            ],
            [
              4.919147193431854,
              52.369374822056535
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              4.919410049915314,
              52.36930767743276
            ],
            [
              4.919410049915314,
              52.36929293835536
            ],
            [
              4.919431507587433,
              52.369266735538915
            ],
            [
              4.9196675419807425,
              52.36918812699636
            ],
            [
              4.919721186161041,
              52.369189764675774
            ],
            [
              4.91974264383316,
              52.36921105450238
            ],
            [
              4.919713139533997,
              52.3692421703844
            ],
            [
              4.91949588060379,
              52.369320778830776
            ],
            [
              4.9194422364234915,
              52.369322416505256
            ],
            [
              4.919410049915314,
              52.36930767743276
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              4.919072091579436,
              52.36993326485086
            ],
            [
              4.919031858444214,
              52.369910337719695
            ],
            [
              4.919174015522002,
              52.36982026673203
            ],
            [
              4.919224977493286,
              52.369844831565075
            ],
            [
              4.919297397136687,
              52.36980716548217
            ],
            [
              4.919313490390778,
              52.36980880313861
            ],
            [
              4.919603168964386,
              52.36998730732725
            ],
            [
              4.919533431529999,
              52.37003479914587
            ],
            [
              4.919573664665222,
              52.370074102681265
            ],
            [
              4.9194395542144775,
              52.37015598493436
            ],
            [
              4.919383227825165,
              52.37012978262988
            ],
            [
              4.919302761554718,
              52.37017891193804
            ],
            [
              4.9189916253089905,
              52.36999385792597
            ],
            [
              4.919072091579436,
              52.36993326485086
            ]
          ]
        ]
      }
    }
]
}

**Comment by mikelmaron** [comment]
I am experiencing the same issue.

**Comment by tmcw** [comment]
2bfd52612a6a4a061a4def9cdcafa8cb688ce4d3 should resolve this issue.

**Comment by tmcw** [comment]
Tested with @mikelmaron's input and lgtm, can you test?

**Comment by mikelmaron** [comment]
:+1:

**Comment by tmcw** [comment]
Closing, fixed in referenced commit.
