### ISSUE TITLE
Mobile - read-only?

### ISSUE THREAD

**Issue by mfc-julius** [mapbox/geojson.io#445]
If Google Maps play nicely with touch devices, so should Mapbox...

**Comment by tmcw** [comment]
This is a known upstream issue in Leaflet.draw https://github.com/Leaflet/Leaflet.draw/issues/2

**Comment by mfc-julius** [comment]
Yes, but yet again there's this: https://github.com/yohanboniface/Leaflet.Editable

**Comment by bmcbride** [comment]
@mfc-julius I can personally attest to the fact that @tmcw is great about reviewing and merging PR's!

**Comment by tmcw** [comment]
We have a ticket for switching to leaflet-editable: https://github.com/mapbox/geojson.io/issues/380
