### ISSUE TITLE
Disable saving into anonymous gist

### ISSUE THREAD

**Issue by geocentrum1** [mapbox/geojson.io#448]
Hi guys, is there any possibility to disable saving into anonymous gist. For example, instead of popup "Changes to this map saved to Gist: XY" it will make an alert "Login first"

**Comment by tmcw** [comment]
Why?

**Comment by geocentrum1** [comment]
Because I need to save all changes to single Gist, e.g. for tracking changes. I want to disable saving by anonymous, it is useless.

**Comment by tmcw** [comment]
I really hate the word useless. Do you really mean useless? Doesn't it seem like being able to save to GitHub without logging in - like, for instance, if you don't have a GitHub account - has some use, and thus is not less of it?

Please don't use the word useless.

**Comment by tmcw** [comment]
The workaround is clear: log in.
