### ISSUE TITLE
Drag n Drop Polygons

### ISSUE THREAD

**Issue by julian-d** [mapbox/geojson.io#449]
Hi,
Is it possible to drag n drop complete polygons? If not, this would be a killer feature!
https://google-developers.appspot.com/maps/documentation/utils/geojson/ <- Like using the "Hand" symbol here

**Comment by tmcw** [comment]
Not currently: the proper place to ask would be at Leaflet.draw: https://github.com/Leaflet/Leaflet.draw

**Comment by tomscholz** [comment]
@julian-d #534 Added

**Comment by tmcw** [comment]
Fixed in #534
