### ISSUE TITLE
Accept null for feature ids

### ISSUE THREAD

**Issue by hyperknot** [mapbox/geojson.io#450]
GeoJSON specification says the following about a feature's id:

> If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id".

Which to me means that id is optional.

Geojson.io on the other hand stops parsing the file and throws errors when features have id: null
```
Feature "id" property must have a string or number value
```

If the id is missing the parsing is ok.

This is especially a problem as Python's geojson package always adds id fields to features.

**Comment by sgillies** [comment]
@hyperknot while "id" may be optional, values must be a string or int: https://tools.ietf.org/html/draft-butler-geojson-05#section-2.2. My recommendation: don't use ints, always use strings.

**Comment by hyperknot** [comment]
@sgillies I didn't know that geojson.org is not the most up-to-date source of the specification, can you or the other contributors update the website to mirror the ietf document?

I've implemented the fix in python-geojson and I'm now waiting for the author to accept it.

**Comment by sgillies** [comment]
@hyperknot good idea :+1: . I'm on it.

**Comment by hyperknot** [comment]
BTW, my PR has been accepted to python-geojson, and is now giving valid output in the latest release:
https://github.com/frewsxcv/python-geojson/blob/master/CHANGELOG.rst
