### ISSUE TITLE
Gists > 1 MB still don´t load!

### ISSUE THREAD

**Issue by geocentrum1** [mapbox/geojson.io#456]
Hello, I already read https://github.com/mapbox/geojson.io/issues/364 and already tried some tests but geojson.io is still not able to load GEOJSON from Gist > 1MB which are truncated. I am not able load files neither by "Open-Gist" button nor directly by URL. If I copy&paste source manually into geojson.io, then I am not able to save (overwrite) this into the same gist and it creates a new one.  Please help! Example layer: https://gist.github.com/geocentrum1/6162cda1f4102b232511

**Comment by tmcw** [comment]
This is simply a very big file, which is outside of geojson.io's range. Sorry - luckily there are many tools geared toward bigger data, like QGIS.
