### ISSUE TITLE
Property arrays get concatenated to a string on save

### ISSUE THREAD

**Issue by planemad** [mapbox/geojson.io#457]
Noticed this behavior while working on a geojson with a coordTime array generated from [togeojson](https://github.com/mapbox/togeojson/tree/master/test/data). When you hit the save button on a feature, the array gets converted to a string.

Test data: https://raw.githubusercontent.com/mapbox/geojson-tidy/master/test/walk-1.json

![untitled1](https://cloud.githubusercontent.com/assets/126868/8213688/b117f838-14f1-11e5-87d1-0408d08e214f.gif)

**Comment by tmcw** [comment]
The properties panel only works with singly-nested properties right now - if we wanted it to edit arrays or objects, it would need some work to present them as nested lists and maintain their structure.

**Comment by tmcw** [comment]
Closing, same core issue as #508
