### ISSUE TITLE
Distortion with rotated features

### ISSUE THREAD

**Issue by ktraff** [mapbox/geojson.io#460]
When displaying two features, a polygon `a` (see [geoJSON](https://gist.githubusercontent.com/ktraff/45dae43d750886b88541/raw/2ed8feb9e0d91bbecebf6d3225f285b1ecf63d7e/gistfile1.txt)) and its minimum bounding rectangle `b` (see [geoJSON](https://gist.githubusercontent.com/ktraff/28af6e671d070d0ebb0d/raw/25549f0380710d668981524cfee2ef7c7f90c0ab/gistfile1.txt)), I get the [following result](https://gist.github.com/anonymous/ac09cb6f105d514ef768):

![image](https://cloud.githubusercontent.com/assets/795979/8317561/b7831648-19bb-11e5-8e2a-dcb3587f11ee.png)

The minimum bounding rectangle around the polygon looks more like a parallelogram than a rectangle to me.

However, when I upload these same features to OpenLayers, the distortion is gone:

![image](https://cloud.githubusercontent.com/assets/795979/8317640/48b24e40-19bc-11e5-95fd-bf660ea17019.png)

Is this a projection issue?

**Comment by tmcw** [comment]
> Is this a projection issue?

Yes: your OpenLayers map is in EPSG:4326 or similar, whereas geojson.io is in web mercator. Hence the different display.
