### ISSUE TITLE
Points with marker-color but no marker-type

### ISSUE THREAD

**Issue by stevage** [mapbox/geojson.io#462]
The spec doesn't say you can't have a color without a type, but GeoJSON.io really doesn't like it.

![screenshot 2015-07-06 16 21 01](https://cloud.githubusercontent.com/assets/678344/8516710/32a29792-23fb-11e5-93e2-de044a9ac2a4.png)

![screenshot 2015-07-06 16 21 06](https://cloud.githubusercontent.com/assets/678344/8516698/100fd258-23fb-11e5-9d09-284329ac445f.png)

![screenshot 2015-07-06 16 21 23](https://cloud.githubusercontent.com/assets/678344/8516702/13c7849a-23fb-11e5-9a48-2a8c90b28384.png)

**Comment by bianji1** [comment]
Offline error too

**Comment by chriswhong** [comment]
Support for simplestyle-spec was removed in the recent UI refresh, but others are requesting its restoration, see https://github.com/mapbox/geojson.io/issues/712
