### ISSUE TITLE
Points with numerical marker size make everything disappear

### ISSUE THREAD

**Issue by stevage** [mapbox/geojson.io#464]
1. Add some features
2. Add a marker feature with:

```
"properties": {
  "marker-size": "80"
}
```

Every feature now disappears.

IMHO adding "invalid" style properties should not cause GeoJSON.io to treat the entire document as invalid.

**Comment by tmcw** [comment]
This is a bug, not overeager validation.

**Comment by chriswhong** [comment]
Support for simplestyle-spec was removed in the recent UI refresh, but others are requesting its restoration, see https://github.com/mapbox/geojson.io/issues/712
