### ISSUE TITLE
can't open kml file

### ISSUE THREAD

**Issue by bobcost** [mapbox/geojson.io#466]
I hava kml file that opens fine in google earth but I get the message "Imported 0 features" when I try to open it in geojson.io.  It was originally a polygon shapefile that I converted to kmz then to a kml. Help. Please.

**Comment by tmcw** [comment]
Can you provide the KML file?

**Comment by bobcost** [comment]
sure

thanks

**Comment by tmcw** [comment]
@bobcost looks like you attached the KML file to an email, but GitHub doesn't include it. You'll need to post a link or similar for the KML file to appear here.

**Comment by tmcw** [comment]
Closing; if you can provide the file, go for it - so far the KML file has not been attached.

**Comment by viana-umana** [comment]
> but GitHub doesn't include it. You'll need to post a link or similar for the KML file to appear here.

Hi, i have the same problem, but i totally new in this, i dont know how can i not attached the KML file to an email or how no to do it... can you help me please. Thank you
