### ISSUE TITLE
geojson.io does not automatically understand a crs tag. 

### ISSUE THREAD

**Issue by arahut** [mapbox/geojson.io#467]
I had to convert from EPSG 32643 to 4326 before geojson.io would actually render it properly
Couldn't find a way to tell the site to automatically use a CRS. Also I shouldn't have to because
the crs is already embedded in the geoJSON file.

**Comment by tmcw** [comment]
geojson.io does not parse or reproject data: you'll need to do so beforehand. Unfortunately, projections are a source of extreme complexity both in terms of code and user expectations, and thus are not part of the data format space that geojson.io aims to conquer: please use EPSG:4326 instead.
