### ISSUE TITLE
geocoding fails

### ISSUE THREAD

**Issue by pdgoodman** [mapbox/geojson.io#469]
The geocoding input no longer works and returns "403 (Forbidden)" in the console. Could be solved by switching from the permanent endpoint to the temporary `mapbox.places` endpoint or by using an access token with access to the permanent endpoint.

Traced to https://github.com/mapbox/geojson.io/commit/21b082642b8f25c4f7ad21e3fd5f939f1081f0f3 

cc @camilleanne

**Comment by camilleanne** [comment]
Last week we made some changes to the scope of the token -- looks like `mapbox-places` will be fine going forward.

fixed in #474
