### ISSUE TITLE
Can not find my 1st file made from a csv file.

### ISSUE THREAD

**Issue by SonnyToday** [mapbox/geojson.io#471]
I did hit save , but it is giving me an earlier version.  I ended with over 100 points.

**Comment by SonnyToday** [comment]
I guess I'll do it over again.  But the same thing might happen again.   😕

**Comment by SonnyToday** [comment]
Opps.  I'm new here.

**Comment by tmcw** [comment]
Closing; feel free to re-file an issue with enough detail to debug - like pointing to the specific data that you were trying to use.
