### ISSUE TITLE
Geojson CSS

### ISSUE THREAD

**Issue by pablomp** [mapbox/geojson.io#472]
Save the style with OpenStreetMap GeojsonCSS specification: http://wiki.openstreetmap.org/wiki/Geojson_CSS

**Comment by tmcw** [comment]
Happy to accept pull requests to add support for this format _in addition_ to simplestyle-spec, but this isn't something I'll work on. GeojsonCSS is very 'strawman spec' level: to my knowledge, it has no implementations.
