### ISSUE TITLE
Feature Properties Coherence with Leaflet

### ISSUE THREAD

**Issue by gotjoshua** [mapbox/geojson.io#473]
Greetings! I am currently working with adding geoJSON objects from geojson.io into Timemapper (which uses leaflet for the map component).
I managed to add features that I created in geojson.io into the location field for timemapper, and to get the styles to apply, but:
1) I had to adapt the property names to match Leaflet's
2) I needed to strip the white space/formatting out of the feature

So questions:
1) are your property names arbitrary? (I don't see them anywhere in the http://geojson.org/geojson-spec.html#feature-objects)
2) What do you think about the idea to offer a less whitespace option/mode in the code editor where each feature is on its own line (easy to select and copy)?

I consider to code for both of these in my fork, but I'd like feedback from the maintainers/main contributors before I dive in...

thanks for your consideration,
gotjoshua

**Comment by tmcw** [comment]
>  are your property names arbitrary?

I'm not totally sure what you mean by this. Property names in GeoJSON can be anything. The style properties that geojson.io exports are [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/), the closest & best-adopted GeoJSON has to a styling standard.

> What do you think about the idea to offer a less whitespace option/mode in the code editor where each feature is on its own line (easy to select and copy)?

Sure, I'd accept a pull request that implemented customizable formatting. Right now [here's where we set it](https://github.com/mapbox/geojson.io/blob/6cf3d053b7cbae3f23acbbb54a967a42a8e55b62/src/panel/json.js#L50).

**Comment by gotjoshua** [comment]
Thanks for the prompt reply.

Well, I'll take that as a pseudo-yes ;) to the arbitrary question:
You use a self-maintained styling standard spec... fair enough!

I'm checking over at Leaflet, if they are following another spec (i think their property names are more closely matching CSS - but lets see how they reply).

In the meantime, I'll have a look at a custom formatting option.

cheers...

**Comment by tmcw** [comment]
> You use a self-maintained styling standard spec... fair enough!

I'm the last committer on that document, but there are [5 implementations](https://github.com/mapbox/simplestyle-spec/wiki/Implementations), 2 of them by outside contributors, and 4 authors of the spec. Every spec is arbitrary at first, I'd say that simplestyle-spec is a little more "a spec" than "arbitrary" :)

**Comment by gotjoshua** [comment]
Agreed! Anyway its amazing work you are doing, and I'm glad to have the chance to contribute.
I will go a bit further in my investigation and create a proposal/example that creates coherence for my needs...
Maybe it will be a pull request on the spec, or perhaps an alternative mode in my geojson fork...
let's see!

**Comment by gotjoshua** [comment]
Update:
Thanks for the pointer to the right code block. I managed to hack an alternative formatting that is quite useful for adding geoJSON to a timemapper spreadsheet:
https://github.com/gotjoshua/geojson.io/commit/064bf2663ed183991ce923be8b77c00a7630ab9d

color properties still need to be manually changed so that Leaflet will recognize them. 

But I think I would prefer to make a property map on the timemapper/recline/leaflet side, rather than change geoJSON.io

Anyway my commit works, but it is just a hack for my purposes. It would need some sort of UI toggle to make it useful in the main interface as an alternative formatting mode. For now, if i click the </JSON> tab it will reformat it as usual... and then if i make a change to the map or a single feature it will reformat to the each feature on a single line mode.

**Comment by tmcw** [comment]
> But I think I would prefer to make a property map on the timemapper/recline/leaflet side, rather than change geoJSON.io

Great, let's keep this as-is; you can manage any kind of property scheme in geojson.io.
