### ISSUE TITLE
Broken accents in exported file

### ISSUE THREAD

**Issue by kazes** [mapbox/geojson.io#481]
I used geojson.io to add a table to my data. 
Some entries has accents surch as `"Champs Élysées"`.

It works fine in the table view and I can see all my beautiful french accents in the code tab as well but when I go in the menu "save" > "geojson" (or "topojson"), the dowloaded file has broken accents such as `"Champs-Ã‰lysÃ©es"`

**Comment by tmcw** [comment]
> the dowloaded file has broken accents such as "Champs-Ã‰lysÃ©es"

How are you viewing the file?

**Comment by kazes** [comment]
Oh good question ! 
You're right, it's not the exported file, it's my code editor's default setting (phpStorm) set to "windows-1252"

![image](https://cloud.githubusercontent.com/assets/932133/10489225/684315e4-729c-11e5-9484-ace5fc254d6e.png)

Fixed it, sorry about that :)
