### ISSUE TITLE
editing stacked points

### ISSUE THREAD

**Issue by ungoldman** [mapbox/geojson.io#488]
Hi all, great project, long time user, first time caller.

I realize that in #328 it is written:

> As far as whether this tool should cluster marker, it's unlikely that it will be included, since it makes the core task of editing a little tricky - since you wouldn't be able to immediately edit everything you click on the map, which is currently the case.

But let it be said, the task of viewing individual points that are stacked on top of each other (let alone editing them) is currently nigh impossible, short of resorting to the table view.

Example: http://geojson.io/#id=gist:anonymous/b2a061b242e7800a82ee&map=16/34.1799/-118.1517

There are 37 points with the same coordinates there. Ideally there would be some indication on the map that 37 things are there, and it would be possible to see and edit details for said things. Is it in the scope of this project to make that kind of viewing and editing possible? Would you be open to a PR? Or should I just make a different tool for that?

**Comment by tmcw** [comment]
I'd be open to a PR that implements this in an unobtrusive way.

**Comment by tmcw** [comment]
This would be upstream in [Leaflet.draw](https://github.com/leaflet/leaflet.draw) - closing here, feel free to re-file there.
