### ISSUE TITLE
Improve the map link goes to null island

### ISSUE THREAD

**Issue by planemad** [mapbox/geojson.io#489]
Go here http://geojson.io/#map=6/21.923/-83.650 don't interact with the map. Click **improve the map**, the coordinates of the current location is not passed.

**Comment by tmcw** [comment]
I think this is upstream in Mapbox.js

**Comment by tmcw** [comment]
This was fixed in #494 (thanks @jwass !)

**Comment by jwass** [comment]
@tmcw and thanks to you for taking a look and pushing live quickly.
