### ISSUE TITLE
removal of \ before " for copy paste from GeoJSON nested in JSON

### ISSUE THREAD

**Issue by JJediny** [mapbox/geojson.io#490]
Just one of those few issues that exist but in order to nest JSON within JSON the nested blob of JSON has to escape quotations in order to avoid parsing the string early... An common way around this is for the output to insert a `\` (forward slash)... consider recognizing this with code mirror etc and suggested removal
![image](https://cloud.githubusercontent.com/assets/6350035/12015292/627cbeb6-ad08-11e5-97f8-33b63734ed5c.png)

**Comment by tmcw** [comment]
The request is to escape pasted JSON by default? That would prevent people from pasting GeoJSON and it working, which would be very confusing for them. Your best bet would be to escape the input before trying to use it as JSON.
