### ISSUE TITLE
Iframe sharing error

### ISSUE THREAD

**Issue by sookoll** [mapbox/geojson.io#491]
I seems that bl.ocks.org do not allow sharing it via iframe. Got error:
```
Refused to display 'http://bl.ocks.org/anonymous/raw/235294c72e24d27203b2/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

**Comment by tmcw** [comment]
Are you embedding in a HTTPS page, or a page with CORS? Have you tried embedding on a simple test page?

**Comment by sookoll** [comment]
no, reqular http and no cors enabled. You can see actual error here (estonian, map is end of page):
http://sookoll.ee/blog/kuidas-uuest-xgis-rakendusest-geomeetria-katte-saada

**Comment by tmcw** [comment]
Huh, looks like @mbostock added a header to prevent iframing? Honestly fine with me, the embedding in geojson.io was always a bit half-baked, and I'd be cool with removing it.

**Comment by mbostock** [comment]
That’s correct. I recently added X-Frame-Options. I’m willing to disable it if users want to pay to support bl.ocks.org (and perhaps some exemptions for other open-source contributors), but otherwise given my limited resources I am limiting the use of frames to bl.ocks.org itself.

**Comment by sookoll** [comment]
@mbostock that's for sure You right to do so, no complains from my side. geojson.io should finally create sharing page that users can embed to their sites (if this feature remains). Fast fix would be remove iframe option from sharing.

**Comment by zbryikt** [comment]
@mbostock just a reminder that bost.ocks.org also embeds bl.ocks.org , so some d3 tutorial like [this](http://bost.ocks.org/mike/bar/3/) can't be shown properly. thank you for building bl.ocks.org!

**Comment by mbostock** [comment]
@zbryikt Thanks, fixed!

**Comment by fatemehgholampour** [comment]
using geojson.io in iframe redirect the page!
