### ISSUE TITLE
The Save to Github feature does not save

### ISSUE THREAD

**Issue by Stampere** [mapbox/geojson.io#497]
When I choose save I get the tree to my repos but nothing saves. What step am I missing?

**Comment by tmcw** [comment]
Are you clicking + New File?

![2016-02-18 at 2 22 pm](https://cloud.githubusercontent.com/assets/32314/13155296/09890668-d64b-11e5-8b1c-dc18ebf31408.png)

**Comment by Stampere** [comment]
I don’t see that choice…

[cid:479895E2-B8D5-47EE-AB15-2B03ADDA9BD3]

**Comment by tmcw** [comment]
Are you looking in a repository, in a branch?

**Comment by Stampere** [comment]
I created a repo for this but I don't know how to assign it.

**Comment by tmcw** [comment]
If it's a fresh repository, you'll need to create a branch in it before geojson.io can save a file into that branch.

**Comment by tmcw** [comment]
Did that work? Anything else to report?
