### ISSUE TITLE
Style properties are always saved, even when "not shown"

### ISSUE THREAD

**Issue by stevage** [mapbox/geojson.io#498]
1. Create a point
2. Edit properties
3. Uncheck "Show style properties"
4. Add some other property
5. Save
6. The generated code includes the default styles.

Basically, if the property editor window gets opened, default styles get saved into the file.

**Comment by tomscholz** [comment]
I don't see the problem.

**Comment by stevage** [comment]
The problem is the editor is adding a bunch of SimpleStyle properties which the user didn't ask for, and can't avoid. That would be (maybe) fine if you're generating a file for some application which interprets SimpleStyle, but in most cases, it's just unwanted noise. 

I very often use geojson.io to create sample data, especially for Mapbox-GL-JS, and I don't ever want these properties. 

It makes using the property editor unusable IMHO.

Here's an example of the code generated through the above process:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "marker-color": "#7e7e7e",
        "marker-size": "medium",
        "marker-symbol": "",
        "test": "foo"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          154.3359375,
          66.08936427047088
        ]
      }
    }
  ]
}
```

**Comment by chriswhong** [comment]
style properties were removed in the recent UI refresh, others are requesting them to be restored, see https://github.com/mapbox/geojson.io/issues/712
