### ISSUE TITLE
allow more external sources through Content Security Policy?

### ISSUE THREAD

**Issue by drewda** [mapbox/geojson.io#499]
@tmcw are you open to loosening CSP somewhat? 

After #496, queries like http://geojson.io/#data=data:text/x-url,https%3A%2F%2Ftransit.land%2Fapi%2Fv1%2Foperators.geojson are no longer possible--even though the target URL is serving CORS headers.

![geojson_io](https://cloud.githubusercontent.com/assets/212369/13265729/63934d1c-da29-11e5-9f8b-de729b54934c.png)

**Comment by tmcw** [comment]
Yep, I've been ratcheting things toward the 'much more secure side' and they could maybe move a step or two backward.

**Comment by drewda** [comment]
:+1: thanks, @tmcw.

**Comment by tmcw** [comment]
Loosened connect-src restrictions in 059c105ed960c67d056e7a1c7a4f9d51b818f34f

**Comment by bmcbride** [comment]
@tmcw Any chance of loosening the restrictions for img-src as well? You can no longer add custom basemaps via Meta > Add map layer. Thanks!

**Comment by bmcbride** [comment]
Thanks!
