### ISSUE TITLE
Change layout orientation in table view

### ISSUE THREAD

**Issue by mathieu-pousse** [mapbox/geojson.io#500]
When we are editing the properties in table view, it would be nice to have a way to change the layout orientation. 

With more than 5 columns, it starts scrolling horizontally.

If we could move the table below the map that will be very nice !

Thanks in advance

**Comment by tmcw** [comment]
Would happily accept a PR or link up a project that does this.

**Comment by tmcw** [comment]
Closing; happy to accept PR.
