### ISSUE TITLE
load image overlay?

### ISSUE THREAD

**Issue by titaniumbones** [mapbox/geojson.io#503]
I have some stuudents working on a project with historical maps. The maps are used as an overlay leyer on top of normal google or leaflet tiles. They then add geoJSON objects (markers, lines, & polygons) onto the map, which is currently generated by going on geosjon.io & adding manually.

It would be nice if they could load the image overlay layer before creating the geoJSON.  Would it be pretty straightforward to do that? 

I'm sorry if the answer is somewhere obvious -- I don't know much about either mapbox or geoJSON and have perhaps done a poor job of navigating the docs.  

Thank you!

**Comment by tmcw** [comment]
The ability to specify a custom tile layer in the URL is tracked at https://github.com/mapbox/geojson.io/issues/430 - it's possible but will require some extra thinking to avoid the potential of it being used as a [XSS attack](https://en.wikipedia.org/wiki/Cross-site_scripting). PRs are accepted that would fix that issue. In the meantime, there is a [console api that lets you add new map layers](https://github.com/mapbox/geojson.io/blob/gh-pages/API.md#console-api) with a few lines of JavaScript.

**Comment by andrewharvey** [comment]
> It would be nice if they could load the image overlay layer before creating the geoJSON. Would it be pretty straightforward to do that?

@titaniumbones I can't tell from your message if you know how to do this manually via Meta > Add map layer ? Just posting in case you weren't aware of it.

**Comment by tmcw** [comment]
Closing this ticket to consolidate discussion in #430!

**Comment by gloriamacia** [comment]
I am trying to do exactly this in 2020 from geojson.io web UI (upload a picture and use the borders to create my custom geojson) and cannot find how to do it. #430 could not help me either (still open). Is this solved?
