### ISSUE TITLE
Bug displaying Antarctica locations?

### ISSUE THREAD

**Issue by jxa900** [mapbox/geojson.io#504]
Hello,

The attached GeoJSON renders correctly here:
https://google-developers.appspot.com/maps/documentation/utils/geojson/
but not on geojason.io for locations in Antarctica

Cheers,
Joseph

[RoI.geojson.txt](https://github.com/mapbox/geojson.io/files/209675/RoI.geojson.txt)

**Comment by tmcw** [comment]
Both interpretations are valid, but Google's assumes that geojson has a winding order distinction, so it is less valid.
