### ISSUE TITLE
Select by ID

### ISSUE THREAD

**Issue by danvk** [mapbox/geojson.io#505]
I may just be missing something here, but if I have the ID of a feature, is there a way to select that feature in the geojson.io UI?

My current solution is to switch to the "Table" view and use Cmd-F to find the feature. Clicking the row will bring the relevant feature into view. But this view can be slow to load for large files, and clicking the feature doesn't visibly highlight it in any way.

I'd be happy with a JS console solution here, too!

**Comment by tmcw** [comment]
Hm, indeed, a console API for this would make sense - right now this is barely possible and very verbose in the console, but we could expose a much friendlier interface.

**Comment by tmcw** [comment]
Now possible with window.api.mapLayer:

https://github.com/mapbox/geojson.io/blob/gh-pages/API.md#windowapimaplayer
