### ISSUE TITLE
Dotted lines

### ISSUE THREAD

**Issue by WCCdev** [mapbox/geojson.io#507]
We need to create dotted/dashed lines. Is there an easy way we can do this? At the moment we are drawing small individual lines and leaving a gap between them ....

**Comment by tmcw** [comment]
geojson.io is a tool for editing data, and supports [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0) for styling. simplestyle-spec doesn't support dashes, so geojson.io doesn't either. If you need deeper style control, try a style-focused application like [Mapbox Studio](https://www.mapbox.com/mapbox-studio).
