### ISSUE TITLE
Microsoft Security Essentials says virus found in the archive!

### ISSUE THREAD

**Issue by nandeshnair** [mapbox/geojson.io#509]
![capture](https://cloud.githubusercontent.com/assets/11608218/14912712/9457aae4-0e1b-11e6-9ccb-f4187876cddf.JPG)
![capture](https://cloud.githubusercontent.com/assets/11608218/14914907/1252ef2a-0e2c-11e6-8e9a-f298b36ec55b.JPG)

**Comment by dmofot** [comment]
Is it possible you have something on your computer injecting it into the file?  I just ran it through [VirusTotal](https://www.virustotal.com/en/file/57acc89a0631155c31a2adeaad4c88c0c489e37b6c4018c554bc12cdfa4669e6/analysis/1461938323/) and it got a clean bill of health.
![screen shot 2016-04-29 at 10 07 06 am](https://cloud.githubusercontent.com/assets/5605132/14918525/5f54f636-0df2-11e6-9046-c5376902b2a3.png)
It also specifically checks with Microsoft's antivirus, which gave the thumbs up:
![screen shot 2016-04-29 at 10 09 54 am](https://cloud.githubusercontent.com/assets/5605132/14918556/8c2fb9c0-0df2-11e6-9ed5-87e1be180a49.png)

**Comment by tmcw** [comment]
Yep, this is a problem with your computer.
