### ISSUE TITLE
Command line for local web server

### ISSUE THREAD

**Issue by danvk** [mapbox/geojson.io#510]
The `mapshaper-gui` command recently [got some upgrades](https://github.com/mbloch/mapshaper/releases/tag/v0.3.22). If you run `mapshaper-gui file.geojson`, it will start a local web server and load that file in its UI.

It would be great to have a variant of the `geojsonio` CLI which did something similar: rather than uploading the file to a gist and loading that on geojson.io, it would start a local instance of the site and load the file directly from your disk. This would be faster and would bypass #456.

**Comment by tmcw** [comment]
Would happily accept a PR or link up a project that does this.

**Comment by danvk** [comment]
Great. I'll take a crack at if I get a few spare cycles.

**Comment by ingalls** [comment]
Closing as stale.
