### ISSUE TITLE
If map is blank, automatically zoom to first feature that is entered

### ISSUE THREAD

**Issue by nchammas** [mapbox/geojson.io#512]
Thank you for making such an accessible service.

I have a minor suggestion: When you're starting with a blank map and you paste some data in to the JSON field, it can be difficult to find and zoom to that feature.

There already is a "zoom to features" capability, but a newcomer may not immediately find it. I suggest automatically zooming to that first new feature when it is added to a blank map.

After the first feature, I think it's OK if the map doesn't automatically zoom to subsequently added features.

**Comment by tmcw** [comment]
Thanks Nicholas!

Thanks for the suggestion! I hope that folks are able to find the zoom to features button, or that they know where their GeoJSON lands. Luckily, given the Leaflet style system, even the tiniest feature will still have a solid border around it on the map, so nothing is ever truly invisible.

Zooming automatically can quickly get annoying if implemented incorrectly - if you're copying & pasting different files and want to keep the same perspective, for instance. I'm hesitant to add it for that reason, and optimistic that, though the UX isn't perfect here, geojson.io provides the natural & explicit abilities to zoom to features.

- Tom
