### ISSUE TITLE
Browser is allways crashing

### ISSUE THREAD

**Issue by Kasimir61** [mapbox/geojson.io#514]
Hi, i add complete Waterways (Germany) as KML File into geojson - but by adding some lines and correct missing lines - i need allways wait 10-15 Seconds and most result is, that Browser crashes.
Is there a Way to work with larger Files online and edit them ?

I think the Problem is the lot Datas of all Waterways- the default file has 4-5 MB
What can i do,
thanks for assist
Kasi

**Comment by tmcw** [comment]
Unfortunately not: that's quite a large file. Try using [QGIS](http://www.qgis.org/) or another desktop tool for larger files.
