### ISSUE TITLE
Proxy url requests to support less-than-ideal sources

### ISSUE THREAD

**Issue by timwis** [mapbox/geojson.io#515]
Hey folks, love the tool! I was thinking of making a similar tool for CSVs. One thing I've noticed though with tools like geojson.io or some other csv sites is that if you intend to use them for embedding (which I do, on open data portals), you run into issues when the source file resides on a server that (a) doesn't support CORS, or (b) doesn't use http*s* (assuming the site you're embedding them on does).

So my thought was a reverse proxy to fetch them from the server. Of course, I hate having a server, and it's great when an app can be 100% client-side, static content. Which it looks like geojson.io is. Except gatekeeper for auth. So perhaps there's a case for a similar microservice just for reverse proxying `geojson` files.

Have you guys thought about this already?

**Comment by tmcw** [comment]
You can use an existing proxy like [crossorigin.me](https://crossorigin.me/) or [cors.io](http://cors.io/) for this requirement: they work pretty well and have maintainers with potentially more time on their hands than I do :)
