### ISSUE TITLE
save lat lang draw by rectangle in sql database

### ISSUE THREAD

**Issue by kumudvrin** [mapbox/geojson.io#516]
i want to save lat lang which are diplayed when we  draw any polygon .please help me

**Comment by tmcw** [comment]
Hi!

geojson.io is a web-based tool that lets you draw, upload, and download geospatial data. As a web app, it doesn't have access to a database: what you're looking for is a server-side application that would consume GeoJSON or another format that we generate and would store that in a database. For that, you could start with [express.js](http://expressjs.com/), Django, Ruby on Rails, or many other options.
