### ISSUE TITLE
Preload turf.js on the site for programmatic manipulation of features

### ISSUE THREAD

**Issue by walling** [mapbox/geojson.io#517]
It could be handy to have [`turf`](http://turfjs.org) already preloaded on the site. I tried to include it by dynamically injecting a `<script>` tag, but it refuses because of the Content Security Policy.

This would enable more complex manipulation of the geojson features.

One of my use-cases is to be able to export many polygons as a single multi-polygon, which I can input in another system.

**Comment by wboykinm** [comment]
@walling To avoid feature creep here, have you considered piping features into [dropchop.io](http://dropchop.io/)? It accepts gist IDs the same way that geojson.io does. e.g.:

http://dropchop.io/?gist=e1028889229343fa8ed8a6e74d21f5d0

**Comment by walling** [comment]
Thanks, it looks interesting from the first quick look. I'll check it out further!

Btw. I solved my original issue by creating a small user script for Tampermonkey, which does the processing for me. What I like about geojson.io is that I can copy-paste my GeoJSON back and forth between systems.

I understand that including more libraries is feature creep, so you can just close this issue.

**Comment by tmcw** [comment]
This is already possible, albeit not built-in, but via the console. I've added a tip for how: https://github.com/mapbox/geojson.io/blob/gh-pages/API.md#protips
