### ISSUE TITLE
Can't open .json .geojson from GitHub using Safari

### ISSUE THREAD

**Issue by ihenry** [mapbox/geojson.io#523]
I am trying to open a .json and/or .geojson from github.  I can browse the project tree and see the files in github but I cannot make it open the .json or .geojson files.
See attached screenshot
Using Safari 9.1.2 on OSX 10.11.6
Tested in FireFox and it works first time.

<img width="1241" alt="screen shot 2016-07-28 at 12 16 44" src="https://cloud.githubusercontent.com/assets/582893/17210840/46c12a74-54bd-11e6-996d-20c1cbfb99b9.png">

**Comment by dmofot** [comment]
Have you tried validating the file on http://geojsonlint.com

Are there any specific errors the browser is giving?  If the file is too large or missing coordinates for a feature, it likely won't load.

**Comment by ihenry** [comment]
Yes, the file is valid and the same file loads fine if I use geojson.io in Firefox.
It is a small file, only 4kb.
The only error I can see in the browserweb debugger is this
InvalidCharacterError: DOM Exception 5: An invalid or illegal character was specified, such as in an XML name.

**Comment by tmcw** [comment]
Closing, same as #458 - please provide a specific file for reference.
