### ISSUE TITLE
Integration with geofenceapi.org

### ISSUE THREAD

**Issue by blockjon** [mapbox/geojson.io#526]
GeofenceAPI.org is a hosted geofence engine based on GeoJSON.

I was interested in building a new "Save" option in order to have an ability to save my GeoJSON file into https://api.geofenceapi.org/ ... If I put an upstream PR together with this new "Save" option, will it get accepted?

Thank you,
Jon

**Comment by tmcw** [comment]
Hey Jon,

Sure, if it's of the same style as the save-to-Gist option, I'd accept that PR.

- Tom

**Comment by blockjon** [comment]
https://github.com/mapbox/geojson.io/pull/527

**Comment by tmcw** [comment]
Fixed in #527
