### ISSUE TITLE
Save to CSV saves a blank file

### ISSUE THREAD

**Issue by warvolin** [mapbox/geojson.io#529]
When I click Save > CSV it downloads a blank file.

Here is the JSON I'm using to generate a polygon:

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "Cleveland-Akron (Canton), OH",
      "properties": {
        "name": "Cleveland-Akron (Canton), OH"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -80.91702900000001,
              40.726711
            ],
            [
              -80.86501900000002,
              40.555297
            ],
            [
              -80.92280800000003,
              40.555297
            ],
            [
              -80.94014500000003,
              40.423631
            ],
            [
              -81.269545,
              40.433568
            ],
            [
              -81.33889199999999,
              40.214953
            ],
            [
              -81.62206000000003,
              40.222406
            ],
            [
              -81.61628100000001,
              40.368977
            ],
            [
              -81.71452299999999,
              40.371461
            ],
            [
              -81.70874400000002,
              40.445989
            ],
            [
              -82.18261799999999,
              40.455926
            ],
            [
              -82.17683899999997,
              40.572687
            ],
            [
              -82.62181699999996,
              40.550328
            ],
            [
              -82.62759599999998,
              40.709321
            ],
            [
              -82.72583800000001,
              40.711805
            ],
            [
              -82.72583800000001,
              40.995011
            ],
            [
              -82.829859,
              40.997495
            ],
            [
              -82.847196,
              41.429756
            ],
            [
              -82.90498600000001,
              41.429756
            ],
            [
              -82.82582715625006,
              41.47750773082124
            ],
            [
              -82.70272299999999,
              41.464536
            ],
            [
              -82.6959156298829,
              41.50521224065793
            ],
            [
              -82.58022585253906,
              41.41561134641229
            ],
            [
              -82.48219164990235,
              41.39410338560995
            ],
            [
              -82.35970347924808,
              41.43638989521471
            ],
            [
              -82.01474216406257,
              41.52441755649443
            ],
            [
              -81.74273135449221,
              41.49503661848993
            ],
            [
              -81.30376230175784,
              41.76359551308452
            ],
            [
              -80.80733867919923,
              41.92012273935298
            ],
            [
              -80.55157376733399,
              41.9757859656113
            ],
            [
              -80.518282,
              41.976294
            ],
            [
              -80.518282,
              41.499316
            ],
            [
              -81.003713,
              41.5018
            ],
            [
              -80.99793399999999,
              40.987558
            ],
            [
              -81.08461899999998,
              40.987558
            ],
            [
              -81.08461899999998,
              40.726711
            ],
            [
              -80.91702900000001,
              40.726711
            ]
          ]
        ]
      }
    }
  ]
}`

**Comment by tmcw** [comment]
CSV output only includes Point geometries, because Polygons and other geometry types have no established pattern as CSV. If you'd like to export more complex output, I'd recommend any of the other export options.

**Comment by JivanRoquet** [comment]
@tmcw when exporting a csv, how about exporting the WKT into one column and each property into its own separate column?
