### ISSUE TITLE
Great Britain unable to be displayed on map

### ISSUE THREAD

**Issue by karthikkumarcv** [mapbox/geojson.io#530]
Hello All,

I am unable to view Great Britain as country in map as i am fetching the data from BW and the map is configured to United Kingdom.
How do i replace the Great Britain to United Kingdom in map??
Kindly provide insights on this.
Using Open street map URL
http://tile.openstreetmap.org/{LOD}/{X}/{Y}.png

Thanks and Regards
Karthik Kumar C V

**Comment by tmcw** [comment]
Hi Karthik,

geojson.io is a tool for modifying data _on top_ of the map, and doesn't permit editing actual map data. The map data is derived from OpenStreetMap, and they [apparently adopted UK as a wrapper term for both the island and North Ireland](https://wiki.openstreetmap.org/wiki/Great_Britain). Territorial disputes are typically vague and fiery and opinionated and very much not my area of interest.

You can use a tool like Mapbox Studio, MapPublisher, ArcGIS, or many others to edit basemaps with your choice of boundaries and names.

- Tom
