### ISSUE TITLE
Split Polygon on line

### ISSUE THREAD

**Issue by nessim99** [mapbox/geojson.io#532]
I'm looking for an easy way to take a complicated polygon and split it into other complicated polygons on a line segment. I'm wondering how difficult this would be to implement, since the math of find line intersections seems relatively simple.

**Comment by tmcw** [comment]
Unfortunately this is extremely difficult to do in a general way: splitting lines is simple, but polygons are... complex and topological. This sort of GIS functionality is unlikely to land in geojson.io anytime soon, but you can use JSTS or Turf in JavaScript, or Shapely in Python, to do that.
