### ISSUE TITLE
Authentication with GitHub failed 

### ISSUE THREAD

**Issue by tomscholz** [mapbox/geojson.io#535]
https://geojsonioauth.herokuapp.com/authenticate/7a3c47a3d6efeedd150f
![bildschirmfoto 2016-10-20 um 12 12 15](https://cloud.githubusercontent.com/assets/20381749/19555765/88386a88-96be-11e6-9218-3f9b27a08aee.png)
![bildschirmfoto 2016-10-20 um 12 12 07 2](https://cloud.githubusercontent.com/assets/20381749/19555764/8833bfa6-96be-11e6-97d0-e6ef5a29ef9a.png)

**Comment by tmcw** [comment]
Looks like the heroku app is acting up, I'll look into it today.

**Comment by tmcw** [comment]
Heroku was just having some downtime - this is working again.

**Comment by joaosr** [comment]
I getting the same error in my account now

**Comment by cyrilchapon** [comment]
Confirmed on Chrome @ Mac

> Failed to load https://geojsonioauth.herokuapp.com/authenticate/1d6ace212801b140647e: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://geojson.io' is therefore not allowed access. The response had HTTP status code 503.

```
GET https://geojsonioauth.herokuapp.com/authenticate/1d6ace212801b140647e 503 (Service Unavailable)
xhr.send @ lib.js:2689
xhr.(anonymous function) @ lib.js:2675
module.exports @ site.js:28814
geojsonIO @ site.js:28851
require.168../core/api @ site.js:28832
s @ site.js:1
e @ site.js:1
(anonymous) @ site.js:1
```
