### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by Damorck** [mapbox/geojson.io#538]
Does it come with UTF-8 characters? I´m forced to change the characters manually and hope there´s a better walkaround . Thx for the good work.

**Comment by tmcw** [comment]
I'm not sure if this is a bug report or a question - as far as I know, geojson.io supports the same unicode range as JavaScript. If this is a question: yes, we haven't seen any UTF-8 related bugs. If it's a bug report: please give specifics about what exact data breaks geojson.io (ideally with a link to a complete downloadable example) and what about geojson.io breaks with that data.

**Comment by Damorck** [comment]
It was meant as a bug. I´ usually drag and drop my csv-file and that results in non-supported UTF-8 characters in the JSON-window.  However it works well when opening from the menu.

**Comment by tmcw** [comment]
As I mentioned in the previous issue: please provide an example of specific input that triggers this bug, so as to help me trigger the bug in order to fix or diagnose the issue.

**Comment by Damorck** [comment]
Input-file attached
[map.zip](https://github.com/mapbox/geojson.io/files/567710/map.zip)

**Comment by tmcw** [comment]
Okay - according to the `file` utility, that isn't a UTF-8, but [ISO-8859](https://en.wikipedia.org/wiki/ISO/IEC_8859), which is a separate and incompatible standard. Loading the file into Numbers and exporting as UTF-8 produces [this file](https://gist.github.com/tmcw/2a34028ffbbe15f1f0495e8577fdcfbd), which loads perfectly into geojson.io.

**Comment by Damorck** [comment]
Should have noticed that it was ISO-8859 and not UTF-8. Thx for clearing that out.
