### ISSUE TITLE
Update d3 to v4

### ISSUE THREAD

**Issue by comlaterra** [mapbox/geojson.io#542]
Is this planned to happen any soon? 
I think it would be a great improvement to this already awesome tool.

**Comment by tmcw** [comment]
Thanks for the suggestion! I'm the main maintainer of geojson.io, and this isn't something I'm planning on implementing. d3 v4 is great, but wouldn't have a significant user-facing effect on geojson.io, and would be a lot of work. Happy to review a PR implementing this change, though, if someone else really wants it to happen!
