### ISSUE TITLE
Greater selector zone around points

### ISSUE THREAD

**Issue by joptimus** [mapbox/geojson.io#545]
Hello,

It would be nice to put in place a bigger buffer zone around selecting a point or marker.  Right now I am trying to remove a bunch of random points and lines but since there is no multiple select (such as a control + mouse drag) option I have to remove each one individually.  Trying to select the line is very hard as you have to be directly on it.  Thank you so much, this tool has helped me greatly!

**Comment by tmcw** [comment]
Hi,

Thanks for the issue! This would be a great addition, but is outside of geojson.io's ability - it would need to be implemented in [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw), the component we use for drawing tools. Feel free to open an issue there if you'd like to implement or ask for this.

- Tom
