### ISSUE TITLE
Cannot open renamed gists

### ISSUE THREAD

**Issue by dbaruch** [mapbox/geojson.io#547]
Reproduction steps:

1) Create a gist in geojson.io
2) Access the gist in Github
3) Rename gist in Github
4) Attempt to open renamed file in geojson.io --> does not appear in the gist list

**Comment by tmcw** [comment]
What are you renaming the file to? `.json` or `.geojson` are required for geojson.io to recognize a file as map data.

**Comment by tmcw** [comment]
Closing: more information would be needed to debug this issue.
