### ISSUE TITLE
Convert encoded polyline to GeoJSON

### ISSUE THREAD

**Issue by nvkelso** [mapbox/geojson.io#553]
Google Maps, Mapzen Turn-by-Turn, and other direction services output encoded polylines which are tiny file size but aren't very interoperable. It'd be nice to copy-paste one of into geojson.io using a new "meta" menu option and convert it to GeoJSON.

- https://mapzen.com/documentation/mobility/decoding/#javascript

I was able to do this manually in the console by getting the coordinates out and sandwiching them inside some GeoJSON front and back matter, and verify in geojson.io and then saved to GIST. Would be nice to incorporate this functionality so I don't have to look it up each time.

**Comment by tmcw** [comment]
Hi!

Sure, that's a good idea. PR in #554

**Comment by nvkelso** [comment]
That was fast, thanks!
