### ISSUE TITLE
Embedding map on webpage

### ISSUE THREAD

**Issue by BimboBo** [mapbox/geojson.io#556]
Hello, 

For an event page I want to embed the map in a website I have. The share option only provides a link to a full view of the map. Is it possible to embed the map so that it can be placed on a website where more content is available?

**Comment by tmcw** [comment]
Hi,

No, geojson.io doesn't provide the option to embed a map - but you can follow an example with [Leaflet](http://leafletjs.com/) or [Mapbox](https://www.mapbox.com/mapbox-gl-js/) or others to embed one using JavaScript.
