### ISSUE TITLE
load and write to GitHub organisations

### ISSUE THREAD

**Issue by daanvr** [mapbox/geojson.io#559]
I really appreciate using Geojson.io, it makes my work easier and helps with making my project more open source and crowd-sourceable. 
I am hitting a wall though. I am working on my project on my own for a while now but I want to include more people to edit the map data. So I was trying to figure our to load not from my Gist but from the Github organisation I just started. But it only wants to show my personal files when loading from Github. The same for saving to Github.
I did figure out how to load a file from an organisation by putting it directly in the geojson.io url. but then my collaborators still have to save it as a file and upload it again to the organisation.

Could it be possible to add support for loading & saving to a GitHub organisation repository?
or maybe it is technically not feasible? or maybe there is a better workaround?

Thanks for your help!

**Comment by tmcw** [comment]
Hi @daanvr,

When you authorize GeoJSON.io's access to GitHub, you should see a list like

![image](https://cloud.githubusercontent.com/assets/32314/24326173/d20f8e1c-117e-11e7-84a0-4797c4b132f5.png)

You may need to grant or request access from your organization - when you do, you'll be able to read and write files in it.

**Comment by daanvr** [comment]
It is working, thank you very much @tmcw!
