### ISSUE TITLE
null geometry in geometry collections

### ISSUE THREAD

**Issue by alpha-beta-soup** [mapbox/geojson.io#561]
I have a GeoJSON object as follows:

```
{
  "type": "GeometryCollection",
  "geometries": [
    {
      "type": "Point",
      "coordinates": [
        101.9,
        -15.3
      ]
    },
    null,
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            100.779,
            -15.299
          ],
          [
            100.779,
            -15.297
          ],
          [
            100.779,
            -15.296
          ],
          [
            100.779,
            -15.299
          ]
        ]
      ]
    },
    null,
    null
  ]
}
```

This fails to render with geojson.io

However if I remove the three `null` geometries in the GeometryCollection, it will render.

```
{
  "type": "GeometryCollection",
  "geometries": [
    {
      "type": "Point",
      "coordinates": [
        101.9,
        -15.3
      ]
    },
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            100.779,
            -15.299
          ],
          [
            100.779,
            -15.297
          ],
          [
            100.779,
            -15.296
          ],
          [
            100.779,
            -15.299
          ]
        ]
      ]
    }
  ]
}
```

![screenshot from 2017-04-13 15 43 42](https://cloud.githubusercontent.com/assets/5925045/24989342/04032236-2060-11e7-97a7-3a0df282794e.png)

I know the `GeometryCollection` is generally frowned upon; support for it tends to be quite application-dependent (which is OK, because I have a specific application), but I'm not sure if this case violates the spec:

> A GeoJSON object with type` "GeometryCollection"` is a geometry object which represents a collection of geometry objects.
>
> A geometry collection must have a member with the name `"geometries"`. The value corresponding to `"geometries"` is an array. Each element in this array is a GeoJSON geometry object.

In turn, a "GeoJSON geometry object" is defined as:

> A geometry is a GeoJSON object where the type member's value is one of the following strings: `"Point"`, `"MultiPoint"`, `"LineString"`, `"MultiLineString"`, `"Polygon"`, `"MultiPolygon"`, or `"GeometryCollection"`.
>
> A GeoJSON geometry object of any type other than `"GeometryCollection"` must have a member with the name "coordinates". The value of the coordinates member is always an array. The structure for the elements in this array is determined by the type of geometry.

While this has no mention of `null`, the specification for the `FeatureCollection` is as follows (emphasis mine):

> A GeoJSON object with the type `"Feature"` is a feature object.
>
> - A feature object must have a member with the name `"geometry"`. The value of the geometry member is a geometry object as defined above **or a JSON null value.**

---

Does this mean that `null` geometries are only allowed as the `geometry` of a `Feature`, and not as part of the `geometries` array in a `GeometryCollection`?

Both of the above are successfully validated and formatted with mapbox.geojsonhint.

**Comment by alpha-beta-soup** [comment]
Just as an observation, if instead of using `null`, I use `{"type": "Polygon", "coordinates": []}`, it will render. This workaround likewise enables pygeobuf `geobuf.encode` to function (it also fails with `null` members of `geometries`).

```
{
  "type": "GeometryCollection",
  "geometries": [
    {
      "type": "Point",
      "coordinates": [
        101.9,
        -15.3
      ]
    },
    {"type": "Polygon", "coordinates": []},
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            100.779,
            -15.299
          ],
          [
            100.779,
            -15.297
          ],
          [
            100.779,
            -15.296
          ],
          [
            100.779,
            -15.299
          ]
        ]
      ]
    },
    {"type": "Polygon", "coordinates": []},
    {"type": "Polygon", "coordinates": []}
  ]
}
```

Logic for this based on a reading of [RFC 7946](https://tools.ietf.org/html/rfc7946) section 3.1:

> A GeoJSON Geometry object of any type other than "GeometryCollection" has a member with the name "coordinates". The value of the "coordinates" member is an array.  The structure of the elements in this array is determined by the type of geometry. **GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects.**

But they're strictly not being treated "as null objects" here, because null objects don't seem to work at all.

**Comment by ingalls** [comment]
> Does this mean that null geometries are only allowed as the geometry of a Feature, and not as part of the geometries array in a GeometryCollection?

Yes, null geometries within a GeometryCollection are not supported in geojsonio
