### ISSUE TITLE
can cache the map for using offline?

### ISSUE THREAD

**Issue by fatemehgholampour** [mapbox/geojson.io#563]
using api.mapbox offline??

**Comment by tomscholz** [comment]
I am not a maintainer, but you have to provide a full description of your problem or feature request. The information, that you have provided, is not enough to give you any feedback.

**Comment by tomscholz** [comment]
And I guess you meant cache, not cashe?

**Comment by fatemehgholampour** [comment]
I want use tiles in offline without internet

there is an api that load map  tiles

Get https://a.tiles.mapbox.com/v4/mapbox.streets.json?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXFhYTA2bTMyeW44ZG0ybXBkMHkifQ.gUGbDOPUN1v1fTs5SeOR4A&secure

I want to use it offline

**Comment by ingalls** [comment]
@fatemehgholampour Unfortunately offline map tiles using the Mapbox tile API violates our terms of use. As such geojsonio does not support offline caching.
