### ISSUE TITLE
Generate random points within given area

### ISSUE THREAD

**Issue by TheMangoTrain** [mapbox/geojson.io#570]
Using http://geojson.io, is it possible to generate random points within a selected area (ie a specific polygon)?

Currently, when selecting "Meta/Random: Points", the generated points are random across the entire map however I'd like to limit their area to a 100kmx50km region.

thx

**Comment by ingalls** [comment]
At the moment geojson.io does not support this behavior. This can be accomplished using a library such ash TurfJS.

https://www.npmjs.com/package/@turf/random
