### ISSUE TITLE
unable to complete polygon

### ISSUE THREAD

**Issue by mstolte** [mapbox/geojson.io#571]
I'm trying to create polygons and for some reason, I cannot complete a custom polygon. When I try to complete a polygon, I see a pop-up telling me to click on the point to close the polygon, but nothing happens when I click. I have tried making this work correctly in Chrome and Firefox. There must be something small that I'm missing. Any help with be appreciated! 
![image](https://user-images.githubusercontent.com/29410224/27096116-fb4362b0-503d-11e7-88a8-96d31decbfcf.png)

**Comment by cclough** [comment]
getting this as well

**Comment by tomscholz** [comment]
Can you check your browser console for any errors?

**Comment by mathieuripert** [comment]
I have the same issue, and though no errors in the console

**Comment by tomscholz** [comment]
^^ I am just seeing that what @mstolte is trying to create is not a polygon. It's a line.

**Comment by tomscholz** [comment]
## Polygon
![nhageqj - imgur](https://user-images.githubusercontent.com/20381749/31680870-e8743c90-b375-11e7-9d15-1f8edb7c7bf8.gif)
## Line
![qum3dby - imgur](https://user-images.githubusercontent.com/20381749/31680871-e896cc7e-b375-11e7-92b5-254c64ce5265.gif)

**Comment by mathieuripert** [comment]
makes sense! thanks
