### ISSUE TITLE
Polygon appears to import, then does not display

### ISSUE THREAD

**Issue by MaloneyMC** [mapbox/geojson.io#575]
I'd like to select in reference to a polygonal boundary. To upload the boundary, I transformed the shapefile to the accepted formats of csv or kmz, but they wouldn't upload (I select the file, the menu disappears, but nothing happens). So I made it a geojson and uploaded that, at which point there's a popup that says: "Imported 1 features" -- but then the site zooms the map very far out, doesn't display the feature when zoomed in, and zooms out again if Zoom to Feature is used. I've tried checking and changing the coordinate system. The different versions of the files display correctly in ArcMap. I've also tried different browsers. Any advice on what to check or try next would be appreciated. Thanks in advance.

**Comment by yennanliu** [comment]
I have the similar issue...
i.e. how to import polygon csv to geojson.io and plotting

**Comment by chriswhong** [comment]
Closing as stale, please update the issue if you're still experiencing this error
