### ISSUE TITLE
OpenCycleMap layer needs API key

### ISSUE THREAD

**Issue by mvl22** [mapbox/geojson.io#577]
The (very useful) OpenCycleMap layer is reporting that requests are not using an API key, which has been recently introduced:

![screen shot 2017-07-28 at 13 53 18](https://user-images.githubusercontent.com/361423/28718084-57163a14-739c-11e7-8663-32067522d9af.png)

**Comment by tomscholz** [comment]
bump

**Comment by sgillies** [comment]
The geojson.io site has minimal maintenance at this time and we missed the new API key requirement when it occurred, that's all.

Users of this software who are running their own instance of geojson.io can add an API key at https://github.com/mapbox/geojson.io/blob/gh-pages/src/ui/layer_switch.js#L27.

@tomscholz @mvl22 for the geojson.io site itself, it's probably for the best to remove the OCM layer now that it's gone commercial (which I totally understand and blame no one for). I don't believe that geojson.io qualifies as a hobby site, we should be paying for access, and paying for the web's free access to OCM tiles isn't part of geojson.io's mission.

**Comment by gravitystorm** [comment]
I was contacted by a couple of people related to this. Just to say that if you would like a Thunderforest API Key for geojson.io (while letting other deployments register for their own API Key) then feel free to get in touch - I'd be happy to discuss it further.
