### ISSUE TITLE
I think a copy button is needed for JSON

### ISSUE THREAD

**Issue by Ardeshir81** [mapbox/geojson.io#582]
HI! Thanks for this great app.
Its all fine, but I'm thinking of a minor improvement, maybe add a `copy` icon on top right corner (or everywhere else) of the JSON section, so by clicking it, the whole thing is copied.
Currently you can do it using `CTRL + A, CTRL + C` or simply selecting all by mouse, but a "buttonic" option would be fine too. Thanks : )

**Comment by marisid** [comment]
Hey - sounds good! @emilyb7 and I will be working on that :)

**Comment by aaj013** [comment]
I can make a try for that :+1:

**Comment by ajeg** [comment]
That sounds like a great option. Was this ever developed? I don't 'see' a copy button anywhere, but maybe I'm missing it?

**Comment by sgillies** [comment]
This feature was never developed.

**Comment by ajeg** [comment]
So GeoJson.io is no longer being developed?

**Comment by sgillies** [comment]
@ajeg read the readme please.
