### ISSUE TITLE
Properties do not work in reactJS application

### ISSUE THREAD

**Issue by abhaychitnis** [mapbox/geojson.io#585]
I have created a layer geometry type "points" using geojson.io. The properties I use for each of these points is as follows : 
```
{
      "type": "Feature",
      "properties": {
        "marker-color": "#00ff40",
        "marker-size": "medium",
        "marker-symbol": "water"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.79173278808594,
          18.555461670891138
        ]
      }
    },
```
I use this to render the layer in my ReactJS application. I am not using any react specific component to render the map. Instead I am using the reference to google map to define map attributes. 

The layer renders correctly with all the points marked at the right places. However the points are displayed in google default marker symbol. The properties defined above are completely ignored. I seem to be missing something basic. Let me know what have I missed.

**Comment by ingalls** [comment]
@abhaychitnis The styling used for GeoJSON.io is the [Simply Syle Spec](https://github.com/mapbox/simplestyle-spec). As far as I am aware this is not supported by Google.
