### ISSUE TITLE
Wrong Postcodes

### ISSUE THREAD

**Issue by nigelgjones** [mapbox/geojson.io#586]
We have developed a simple zone calculator for a freight company to provide delivery zones within NZ. We are using Mapbox based on Google. We find in most cases it is correct apart from sometimes the postcode delivered is wrong. For example using http://zones.dartfreight.co.nz/
and entering in 8 Te Oneroa Way, Auckland, New Zealand gives the zone correcly but the postcode says 0792. Using NZ Post gives a postcode of 0630.

We need the information to reflect the true postcode shown on the postcode finder. It seems Google information is out of date.

Can we hook into the Rate finder API to get the postcode details correctly?

**Comment by ingalls** [comment]
Hello, this repo is for tracking issues with geojson.io.

If you are using our geocoding API commercially and have discovered a problem or want to use our geocoding API, please contact help@mapbox.com.
