### ISSUE TITLE
Marker title attribute incorrectly escaped

### ISSUE THREAD

**Issue by davidearl** [mapbox/geojson.io#590]
If you have a title element in a point feature's properties, it is included in the title for the marker, so you get to see it when you hover over the marker (great). However if you include an ampersand in the title, it gets displayed as ampersand-a-m-p-semicolon, i.e. the html element (not so good). It is shown correctly in the properties box. Presumably there's a double escape going on somewhere.

e.g. 
<pre>
    {
      "type": "Feature",
      "id": 577,
      "properties": {
        "title": "Something & Something else"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          0.0,
          52.0
        ]
      }
    }
</pre>

**Comment by chriswhong** [comment]
It's up for debate whether we support simplestyle moving forward.  Closing, please see https://github.com/mapbox/geojson.io/issues/712
