### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by shayo** [mapbox/geojson.io#591]
I love the online UI at http://geojson.io/
Is it possible for you to increase the maximal zoom level? We are using it for generating some maps and we need more zoom to edit fine features.
Thanks!

Alternatively, can you please point me to where I will need to edit the code to allow more zoom?

**Comment by tomscholz** [comment]
See this comment https://github.com/mapbox/geojson.io/issues/567#issuecomment-299009562

TL;DR: The zoom level depends on where you are.

**Comment by tomscholz** [comment]
Also: The zoom level has little/nothing todo with geojson.io, since the website only takes use of openstreetmap and thunderforest apis.
