### ISSUE TITLE
Option to hide the JSON/Table/Help pane via URL Parameter

### ISSUE THREAD

**Issue by mjkruk** [mapbox/geojson.io#593]
Would be great to have an additional URL param that will change body class="fullscreen" for hiding the JSON/Table/Help panel.

**Comment by ajeg** [comment]
I would also love to see this option.

**Comment by ajeg** [comment]
So GeoJson.io is no longer being developed? I ask because this was closed with a "wontfix", sounds kind of final.

**Comment by sgillies** [comment]
See the readme.
