### ISSUE TITLE
No longer able to Authenticate with GitHub

### ISSUE THREAD

**Issue by kbtbc** [mapbox/geojson.io#596]
I logged out of geojson.io with my github account and am now unable to log back in to open my gists.   Even if I log out of github, and try to re-authenticate through geojson.io -- it has me do the github login on my account, then says 'unable to authenticate' .

The error:  No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://geojson.io' is therefore not allowed access.

From dev console:

```
lib.js:2689 GET https://geojsonioauth.herokuapp.com/authenticate/14f775c21580c1865f8e 503 (Service Unavailable)
xhr.send @ lib.js:2689
xhr.(anonymous function) @ lib.js:2675
module.exports @ site.js:28814
geojsonIO @ site.js:28851
require.168../core/api @ site.js:28832
s @ site.js:1
e @ site.js:1
(anonymous) @ site.js:1
/?code=14f775c21580c1865f8e#map=2/20.0/0.0:1 Failed to load https://geojsonioauth.herokuapp.com/authenticate/14f775c21580c1865f8e: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://geojson.io' is therefore not allowed access. The response had HTTP status code 503.

```

**Comment by sgoodm** [comment]
confirming this is still an issue

**Comment by bfeldman89** [comment]
Same issue for me right now 😒
![shook](https://media.giphy.com/media/DENtTUGBDXtxm/giphy.gif)

**Comment by bhousel** [comment]
same as #620 

---
Note: development of geojson.io is currently paused. You may be interested in the new fork at https://geojson.net. Until development restarts, please refrain from adding issues to the tracker.
