### ISSUE TITLE
Add gallery of example sample maps

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#599]
Add a link to the wonderful work others have created so we can see all the power...

Currently the only examples are http://geojson.io/#id=github:benbalter/dc-wifi-social/blob/master/bars.geojson&map=14/38.9140/-77.0302 and one more, found deep in the right panel, and just as examples for remote calls, not general examples, as seen on the "get inspired" section of http://umap.openstreetmap.fr/ .

**Comment by bhousel** [comment]
Oh cool, you found  http://umap.openstreetmap.fr/  already, which is what you're looking for.
