### ISSUE TITLE
Hyperlink also names, not only arrows, on Open > GitHub

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#602]
Click Open > GitHub. I see
▼積丹尼 Dan Jacobson
▶circe
▶mymaps
OK good. But I can only click the arrows above.
The **names** should be also part of the same hyperlink.

The result is I must aim the mouse with a steady hand to click the arrows.

**Comment by chriswhong** [comment]
No longer relevant after UI refresh
