### ISSUE TITLE
Open > GitHub cursor wrong

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#603]
I click `open` and see,
```
GitHub
▼積丹尼 Dan Jacobson
▶circe
▼mymaps
▼master
LICENSE
N.geojson.gz
O.geojson
README.md
map1.geojson
▶spectre-meltdown-checker
▶wayback
```
When the pointer is placed on any of them, the pointer symbol is all wrong. You are using the text entry symbol "I" instead of a correct 'arrow when over something clickable."

**Comment by jidanni** [comment]
By the way, clicking my 3000 point .geojson file did nothing. But that is an issue for #600 .

**Comment by chriswhong** [comment]
No longer relevant after UI refresh
