### ISSUE TITLE
github.com cert not valid for geojson.io

### ISSUE THREAD

**Issue by sgillies** [mapbox/geojson.io#607]
From Chrome:

> This server could not prove that it is geojson.io; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by tmcw** [comment]
geojson.io is hosted on GitHub pages, which still doesn't have support for SSL on custom domains. It'd be appropriate to switch to something else, like Mapbox's publisher stack, Netlify, Zeit, etc, to have SSL-capable hosting.

**Comment by bhousel** [comment]
> geojson.io is hosted on GitHub pages, which still doesn't have support for SSL on custom domains. It'd be appropriate to switch to something else, like Mapbox's publisher stack, Netlify, Zeit, etc, to have SSL-capable hosting.

Oh!  SSL is supported now on GitHub pages.  Currently geojson.io is set up with older style A records pointing to GitHub IPs.  However as of a few months ago, we can switch to a CNAME or ALIAS record and GitHub can LetsEncrypt it for us.  

Maybe @miccolis can help change this?
