### ISSUE TITLE
Github OAuth permissions revision?

### ISSUE THREAD

**Issue by urschrei** [mapbox/geojson.io#608]
The Github OAuth login states that Tom MacWright is the application owner, and asks for extremely broad permissions (read and write for all public and private repos and gists). The ownership issue is probably nbd for most of us, but I wonder whether a more restricted permissions set is possible?

**Comment by bhousel** [comment]
I agree, that is probably much broader than it needs to be - thanks for reporting @urschrei

**Comment by tmcw** [comment]
Would be useful to [read some of the archives here](https://github.com/mapbox/geojson.io/issues/506) - if the default is public only, the lack of private will be perceived as a bug. If the default is private, then the inclusion of private will be perceived as a security problem. You'll likely need to implement two login buttons with two different permissions setups if you want to satisfy a plurality.

**Comment by urschrei** [comment]
Ah, I wondered whether the issue had come up before, but when I searched for "permissions" and "oauth" nothing came up. Bah.

**Comment by guyarad** [comment]
With Google OAuth you can ask for permissions gradually. Start with public and extend to private when needed. It's possible with Github?

**Comment by rosshemsley** [comment]
*A datapoint:*

For me this was a deal-breaking issue and I decided to abandon geojson.io.

You can use github's built-in gist mechanism, which can render geojson natively, this was sufficient for me.

**Comment by chriswhong** [comment]
We opted to remove auth for the time being and will rethink if/how to bring if back at a later date.
