### ISSUE TITLE
Anonymous gist creation has been removed by GitHub

### ISSUE THREAD

**Issue by pathmapper** [mapbox/geojson.io#609]
https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation

After March 19, 2018 `Save in GitHub Gist` could be handled the same way like `Save to GitHub Repository` is handled currently  ("You must authenticate to use this API.").

**Comment by sgillies** [comment]
@pathmapper thanks for the suggested solution.

**Comment by chriswhong** [comment]
no longer relevant after UI refresh
