### ISSUE TITLE
"Feature": Error when "properties" is "null"

### ISSUE THREAD

**Issue by cweiske** [mapbox/geojson.io#610]
The GeoJSON specification allows NULL values for the `properties` key:

> A Feature object has a member with the name "properties".  The value of the properties member is an object (any JSON object or a JSON null value).

https://tools.ietf.org/html/rfc7946#section-3.2

However when opening a file with `null` properties, I get an error:

```
Invalid JSON file: TypeError: can't convert null to object
```

Example file that triggers this error: http://p.cweiske.de/556

Happens in Firefox 59.

**Comment by chriswhong** [comment]
The example provided loads without issue now.

**Comment by cwarden** [comment]
Opening a geojson file with null properties is failing again, with "Invalid JSON file: TypeError: Cannot convert undefined or null to object", including the example file linked above, http://p.cweiske.de/556.
