### ISSUE TITLE
Share doesn't seem to be working

### ISSUE THREAD

**Issue by jordanranson** [mapbox/geojson.io#611]
After drawing a simple shape of any type (polygon, polyline, etc) and clicking the Share link in the main menu at the top of the screen, I always get an error: `Could not share: an error occurred: Validation Failed`

If I look in the console, I'm getting a 422 code back from this API: `https://api.github.com/gists`

This is the response:
```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Gist",
      "code": "missing_field",
      "field": "user"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

This happened on a fresh page load, with a single segment polyline, as well as a 5 pointed polygon, without me having changed anything in the source/editor.

Edit: This happens logged in as well as logged out/anon.

**Comment by pedros007** [comment]
#609 seems to point to the problem: [anonymous gist creation has been deprecated](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/).

**Comment by jordanranson** [comment]
So is this going to be looked at any time soon?

**Comment by sgillies** [comment]
@jordanranson I'm closing this one in favor of #609, which has a suggested solution. I can't yet provide a time frame for fixing this.
