### ISSUE TITLE
geojsonioauth.herokuapp.com shutting down April 1

### ISSUE THREAD

**Issue by tmcw** [mapbox/geojson.io#612]
geojson.io's auth still runs on my personal heroku account. I'm happy to transfer it to a Mapbox heroku account, or someone at Mapbox can run their own (it's just a vanilla [gatekeeper](https://github.com/prose/gatekeeper) instance). Setting April 1 as the sunset date for this instance, as well as localhostauth.herokuapp.com, the server that local development relies on for GitHub authentication.

**Comment by sgillies** [comment]
@tmcw thanks for the assistance on this. The Heroku apps are running under my account today and will be transferred to a Mapbox Heroku account soon.
