### ISSUE TITLE
Utf-8 support when saving

### ISSUE THREAD

**Issue by aanders77** [mapbox/geojson.io#613]
When saving a file which contains letters like e.g. š, they become unencoded in the resulting map.geojson. I.e. they look like this: Å¡

**Comment by sgillies** [comment]
@aanders77 encoding has been reliable for a long time. I tried to reproduce the issue and failed, so I'm confident we don't have a regression.

Here's a feature I created in geojson.io:

<img width="985" alt="untitled" src="https://user-images.githubusercontent.com/33697/38204074-a11c849e-365e-11e8-9714-15900b21b70a.png">

And here is my analysis of the saved .geojson file:

```
$ python
>>> import json
>>> with open('/Users/sean/Downloads/map.geojson') as f:
...     collection = json.loads(f.read())
...
>>> for feat in collection['features']:
...     print(feat['properties']['name'])
...
Hîöé
```

The site's javascript is running in your browser, so I suspect this has something to do with your browser's preferences. I'm using Firefox 59.0.1 here and the page's text encoding is UTF-8.
