### ISSUE TITLE
No instructions to support the attributes of simplestyle-spec used in geojson.io with leafletjs

### ISSUE THREAD

**Issue by gouessej** [mapbox/geojson.io#615]
Hey

When I modify the color of a pinpoint in a map in geojson.io, it inserts an attribute named "marker-color" into the generated geojson source code. I use [this tutorial](http://leafletjs.com/examples/geojson/), this is my main source of inspiration, particularly this line:
`L.geoJSON(geojsonFeature).addTo(map);`

What is the most straightforward solution to take into account simplestyle-spec's marker color when rendering with leafletjs a map generated by geojson.io?

**Comment by sgillies** [comment]
@gouessej you'll need to write a callback that acts on the `marker-color` property. See the section on style after "Alternatively, we can pass a function that styles individual features based on their properties." under http://leafletjs.com/examples/geojson/.

Closing now as this is not a geojson.io issue.

**Comment by gouessej** [comment]
@sgillies Thank you. As I use some markers as features (they aren't polygons), the color attribute is undefined, your very first suggestion doesn't work.

This is the least ugly solution I've found by using onEachFeature:
```
var redIcon = L.icon({iconUrl: 'pin-m+ff0000.png'});
var greenIcon = L.icon({iconUrl: 'pin-m+00ff00.png'});
var blueIcon = L.icon({iconUrl: 'pin-m+0000ff.png'});
L.geoJSON(geojsonFeature, {
        onEachFeature: function (feature, layer) {
            if (feature.properties["marker-color"] !== undefined) {
                switch (feature.properties["marker-color"]) {
		    case "#ff0000": {
                        layer.setIcon(redIcon);
			break;
		    }
		    case "#00ff00": {
			layer.setIcon(greenIcon);
			break;
		    }
		    case "#0000ff": {
			layer.setIcon(blueIcon);
			break;
		    }
		}
            }
        }
}).addTo(map);
```
