### ISSUE TITLE
Idea: support the "encoded polyline" format as url parameter

### ISSUE THREAD

**Issue by jtheuer** [mapbox/geojson.io#616]
Hey,

Thanks for the great work! What do you think about also supporting the [Google Polyline Encoding format](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) for the `data=` [url parameter](https://github.com/mapbox/geojson.io/blob/gh-pages/API.md#url-api)?

Currently I convert them to geojson before, but the polyline format would be more compact / support larger geodata.

**Comment by sgillies** [comment]
@jtheuer we appreciate the feature request, but a backlog of bug fixes means this will be low priority for now.

**Comment by bhousel** [comment]
closing as wontfix
---
Note: development of geojson.io is currently paused. You may be interested in the new fork at https://geojson.net. Until development restarts, please refrain from adding issues to the tracker.
