### ISSUE TITLE
Support MultiPolygon editing

### ISSUE THREAD

**Issue by PaulDMendoza** [mapbox/geojson.io#617]
I'm trying to edit this file. 

http://leafletjs.com/examples/choropleth/us-states.js

I've removed the variable declaration and semicolon at the end to convert it to JSON and that's fine. When I put it into GeoJSON.io it actually loads the file fine. But when I go to edit one of the states, it doesn't work and starts throwing lots of errors. 

![image](https://user-images.githubusercontent.com/1039795/38372025-b634ac6c-38a2-11e8-8120-deaa0b265bf1.png)

This is using Chrome 65

I'm encountering this error a lot today with lots of different geojson files. Here is an example of another file I"m seeing this error with. 
 
[QC.json.txt](https://github.com/mapbox/geojson.io/files/1880962/QC.json.txt)

**Comment by chriswhong** [comment]
Closing, MultiPolygon editing is working now.
