### ISSUE TITLE
Failing save locks interface

### ISSUE THREAD

**Issue by HolgerJeromin** [mapbox/geojson.io#618]
I changed a file and clicked "save" (menu title) instead of "save geojson".
I got an info that auth failed or something like that.
But the darken layer (::after pseudo element) was not cleared.
So i had no way to save my change again.

i removed the ::after in dev tools and saving as geojson was possible, but other users would have a data loss.

**Comment by chriswhong** [comment]
Closing as stale, please let us know if you're still experiencing this with the latest version.
