### ISSUE TITLE
GitHub Authentication Fail

### ISSUE THREAD

**Issue by jacksonrya** [mapbox/geojson.io#620]
Simple to recreate (for me, at least).
1. Attempt to 'login' to GitHub
2. Successfully login in @ GitHub
3. Wait ~5 seconds for alert notification of 'Failed Authentication'

I am using this app for a class that features this app in their tutorials. This is a common issue among other students as well.

**Comment by bfeldman89** [comment]
@jacksonrya same issue for me

**Comment by Kangarulez** [comment]
same here @jacksonrya

**Comment by mashaal** [comment]
Still experiencing this issue

**Comment by develar** [comment]
@tmcw Could you please take a look? https://github.com/tmcw/geojson.net/issues/1 is closed, but this issue is still actual. It is not possible to share without auth.

**Comment by tmcw** [comment]
geojson.net is a separate project - it does not patch this project.
