### ISSUE TITLE
Allow outbound hyperlinks

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#621]
We see the example,
http://geojson.io/#data=data:text/x-url,http%3A%2F%2Fapi.tiles.mapbox.com%2Fv3%2Ftmcw.map-gdv4cswo%2Fmarkers.geojson

Alas
1. There is no way to see the full names of most airports without resorting to the mouse to reveal the hidden words that go beyond the box.
2. There is no provision for a hyperlink one could click to e.g., visit an airports website.

Conclusion: geojson.io is for data that fits on one short line and has no hyperlinks.

**Comment by bhousel** [comment]
sorry, closing as wontfix - geojson.io is not meant to be a full featured map that you share with people, so adding linkable POIs is pretty far out of scope.

You could probably achieve what you want with a tool like  https://umap.openstreetmap.fr/
