### ISSUE TITLE
Can't edit properties on object with GeometryCollection

### ISSUE THREAD

**Issue by stevage** [mapbox/geojson.io#627]
I'm not certain that the GeometryCollection is the issue, but see here:

http://geojson.io/#id=gist:stevage/0476d68f350778acc3b67d57d66bf7d2&map=4/-32.62/127.09

Click on the feature (which consists of the line and the point). Add properties. Try to save. Can't.

Add a new feature, add properties there. Saving works fine.

**Comment by osmaa** [comment]
Also it seems trying to edit a Polygon inside a GeometryCollection fails with

```
Uncaught TypeError: Cannot set property 'previousOptions' of undefined
    at NewClass._enableLayerEdit (lib.js:9340)
```

http://geojson.io/#id=gist:osmaa/97c6a8e6dacf1974b5bdbef1b48eed9e&map=15/60.3178/24.9746

**Comment by Thefamir** [comment]
The same issue with trying to edit the properties. Can't edit it, here: 
http://geojson.io/#map=7/41.775/65.204

**Comment by chriswhong** [comment]
Closing, looks like property edits on GeometryCollections are working now.
