### ISSUE TITLE
GeoJSON authentication keeps failing

### ISSUE THREAD

**Issue by naljassar** [mapbox/geojson.io#628]
Every time I try to hit the "login" button at the top right of geojson.io when I am logged into my github account, nothing happens. The page refreshes and I am still not logged into geojson. When I click a couple of more times, I get this error: "Authentication with GitHub failed"

How do I fix this so I can use geojson?

**Comment by bhousel** [comment]
Closing as a dup of #620 

---
Note: development of geojson.io is currently paused. You may be interested in the new fork at https://geojson.net. Until development restarts, please refrain from adding issues to the tracker.
