### ISSUE TITLE
"Feature": Error when "geometry" is missing.

### ISSUE THREAD

**Issue by DarinMacRae** [mapbox/geojson.io#630]
The map works fine if the geometry is "null" but if the JSON serializer doesn't include null values then the map just won't show anything. Adding the geometry back in with a null value fixes it but the map should allow for either due to the common serializer setting of not including null values.

e.g. JsonSerializerSettings.NullValueHandling = NullValueHandling.Ignore;

**Comment by sgillies** [comment]
@DarinMacRae I'm sorry, but we're not going to do anything about this one. The GeoJSON format does require a feature to have a geometry object, even if only `null`.
