### ISSUE TITLE
Support https on http://geojson.io

### ISSUE THREAD

**Issue by alecf** [mapbox/geojson.io#632]
with the new chrome release, http://geojson.io is reporting as "not secure"

![image](https://user-images.githubusercontent.com/135340/43861821-d49064fe-9b0c-11e8-8116-cfa7bf10c7fd.png)

I absolutely realize this has no bearing on functionality and that the actual data doesn't need to be secure, but I occasionally direct customers here to make geojson files, and now it feels like I'm directing people to an "insecure" site.

**Comment by jalessio** [comment]
Information on enabling HTTPS for custom domains on Github pages:
* https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
* https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by bhousel** [comment]
same as #607 

---
Note: development of geojson.io is currently paused. You may be interested in the new fork at https://geojson.net. Until development restarts, please refrain from adding issues to the tracker.
