### ISSUE TITLE
Can we get the borders of a region if we search them in the search box ? 

### ISSUE THREAD

**Issue by debanjanxy** [mapbox/geojson.io#634]
If we search a place in the search box, it goes to the corresponding lat,lng of that place. But the borders of that place is absent. Is there a way to get the borders of a place or region ?
Thank you.

**Comment by chriswhong** [comment]
Search is powered by the Geocoding API, which doesn't return boundaries.  I think the answer right now is to source boundary data elsewhere and open it in geojson.io.
