### ISSUE TITLE
Additional map layer - set zoom/size

### ISSUE THREAD

**Issue by falstaffjobs** [mapbox/geojson.io#635]
I would like to add a map layer for drawing regional polygons:

but the image is always displayed in tiles, is there any way to set the size of the additional map layer?

![screenshot 2018-10-03 16 40 46](https://user-images.githubusercontent.com/10829964/46418094-52b64c00-c72b-11e8-9386-d67ac1260352.png)

thanks for your help

**Comment by chriswhong** [comment]
Looks like you added an image, not a raster tile layer.  There's no way to overlay an image on the map
