### ISSUE TITLE
Authentication with GitHub failed

### ISSUE THREAD

**Issue by dshefer** [mapbox/geojson.io#636]
I set up an account on GitHub so I can save my maps but get an error message when trying to log in - 
"Authentication with GitHub failed"

**Comment by sgillies** [comment]
@dshefer this is an issue that comes and goes. I recommend trying again.

**Comment by dshefer** [comment]
Tried several times since your email. Still cannot log in.

Thanks,

**Comment by AndreSteenveld** [comment]
I've been having this issue as well today and got a 503 in my browser console:

```
Failed to load https://geojsonioauth.herokuapp.com/authenticate/<...snip...>: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://geojson.io' is therefore not allowed access. The response had HTTP status code 503.
```
