### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by zyp001a** [mapbox/geojson.io#639]
I tried these version of node for `npm install`
* node/8.*
* node/9.11.2
* node/10.13.0
* node/11.2.0
they all failed in building process.
only node/6.14.4 works

**Comment by jackyq2015** [comment]
Same issue here:
`531 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
531 verbose stack Exit status 1
531 verbose stack     at EventEmitter.<anonymous> (/home/cui/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
531 verbose stack     at emitTwo (events.js:126:13)
531 verbose stack     at EventEmitter.emit (events.js:214:7)
531 verbose stack     at ChildProcess.<anonymous> (/home/cui/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
531 verbose stack     at emitTwo (events.js:126:13)
531 verbose stack     at ChildProcess.emit (events.js:214:7)
531 verbose stack     at maybeClose (internal/child_process.js:915:16)
531 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
532 verbose pkgid contextify@0.1.15
533 verbose cwd /media/cui/deve/src/geojson.io
534 verbose Linux 4.15.0-43-generic
535 verbose argv "/home/cui/.nvm/versions/node/v8.15.0/bin/node" "/home/cui/.nvm/versions/node/v8.15.0/bin/npm" "install"
536 verbose node v8.15.0
537 verbose npm  v6.4.1
538 error code ELIFECYCLE
539 error errno 1
540 error contextify@0.1.15 install: `node-gyp rebuild`
540 error Exit status 1
541 error Failed at the contextify@0.1.15 install script.
541 error This is probably not a problem with npm. There is likely additional logging output above.
542 verbose exit [ 1, true ]
`
Maybe that's the reason to move to geojson.net?

**Comment by sgillies** [comment]
There are no plans to fix this, but we will add an engines item to the package.json to make the situation more clear.
