### ISSUE TITLE
Translation proposition of geojson io

### ISSUE THREAD

**Issue by CorentinLemaitre** [mapbox/geojson.io#641]
Hello, 
I use geojson.io and try to make it use by more and more people because it is super simple.
To make it even more simple i think translation could be usefull. I am french and ready to do as much as i can for the translation but i don't know how it could be implement in the website then.

**Comment by sgillies** [comment]
@CorentinLemaitre we appreciate the offer, but geojson.io development is paused, and we aren't accepting new features like translation. If the situation changes, we will reopen this issue.
