### ISSUE TITLE
How to import CSV and set coordinates to "Polygon" as area instead of "Points"?

### ISSUE THREAD

**Issue by tophat1986** [mapbox/geojson.io#642]
My data is importing and defaulting to points on coordinates.

I've tried setting a "type" column with "polygon", but this failed.  I can't see any examples on how the CSV should be formatted?  Is there an example?

Cheers

**Comment by RomanGX** [comment]
I have similar problem, even polyline is not working => when saving polyline to csv the csv is empty. It only works for points. Tried several json-csv converters but did not help.

**Comment by RomanGX** [comment]
Just found simple solution. Save your line/polygon as GEOjson (NOT csv) => you will get the file: somename.geojson

This file you can edit/save in e.g. Notepad. At least it worked for my points and polylines
