### ISSUE TITLE
Parse error indication when geometry is empty

### ISSUE THREAD

**Issue by mvl22** [mapbox/geojson.io#643]
The GeoJSON spec seems to permit geometries to be empty:

[RFC 7946](https://tools.ietf.org/html/rfc7946) section 3.1:

> A GeoJSON Geometry object of any type other than "GeometryCollection" has a member with the name "coordinates". The value of the "coordinates" member is an array.  The structure of the elements in this array is determined by the type of geometry. **GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects.**

However, GeoJSON.io's parser flags up an empty LineString geometry container as invalid (see the light red marker next to the line number):

![screen shot 2019-02-08 at 16 07 28](https://user-images.githubusercontent.com/361423/52490155-ff15ac80-2bbb-11e9-84b8-5980730fbe09.png)

Is this considered correct behaviour?

LineString and Point exhibit this behaviour, but Polygon, MultiPoint, Multipolygon, MultiLineString do not.

See also #561 which mentions this as a side-issue to the invalid concept of a 'null' geometry.

**Comment by sgillies** [comment]
I agree that geojson.io should probably be the most forgiving parser and should be able to perform the MAY parts of the spec, but as we state in the readme https://github.com/mapbox/geojson.io/blob/gh-pages/README.md#geojsonio this project is not actively developed at this time. We're only addressing truly harmful issues.

**Comment by mvl22** [comment]
Thanks.

Could you update the README to point the repo to:
https://github.com/tmcw/geojson.net
which (I think) is the new forked repo location.

**Comment by sgillies** [comment]
Done!
