### ISSUE TITLE
Suggestion: Move off .io ccTLD.

### ISSUE THREAD

**Issue by rory** [mapbox/geojson.io#644]
I know this project doesn't have a Code of Conduct, but I suggest moving off the .io ccTLD.

`.io` is for the "British Indian Ocean Territory", and fees go to support the British military occupation, which has carried an effective genocide of an entire people (the Chagossians). A CIA black site is rumored to be operating there.

Funding such racist actions cannot be seen as supporting anti-racism. Yes, it will be inconvenient to move domain and backlinks, but most CoCs "prioritize marginalized people’s safety over privileged people’s comfort", so I urge you to move the domain.

See more:

 * https://en.wikipedia.org/wiki/Expulsion_of_the_Chagossians
 * https://www.chagossupport.org.uk/

**Comment by sgillies** [comment]
It's a fine suggestion, but as we mention in the readme, we're not changing the project except to fix harmful software bugs.
