### ISSUE TITLE
How flatten multi features

### ISSUE THREAD

**Issue by Cyril21800** [mapbox/geojson.io#647]
Hi , 
First of all, thkx a lot for eveything this project is amazing, 
I'm triing to import a KML files of polygons, (working), but i 'm looking to flatt in only one polygone, 
When clicking on "Meta > Flatten Multi Features" button, nothings happen. Do you already use the multi flatten fonction ?
Should i maike sometinhg first ? Load a js file ?
Thx for your help

**Comment by sgillies** [comment]
@Cyril21800 this project is not accepting usage questions right now. 

I hope you can find some help in the following links:

* https://twitter.com/geojsonio/status/509448597352366080
* https://github.com/tmcw/geojson-flatten
