### ISSUE TITLE
server not responding 

### ISSUE THREAD

**Issue by dorbodwolf** [mapbox/geojson.io#648]
In my case,  creating  a simple MultiLineString with two lines and then save it to shapefile(or GeoJSON) can lead to `server not responding` problem,  not to say large features with large nodes...

**Comment by sgillies** [comment]
I think this must have been a transient issue because I cannot reproduce it. I successfully saved a shapefile (as download.zip) a minute ago.

**Comment by dorbodwolf** [comment]
maybe beacuse of my using of vps(shadowsocks)
