### ISSUE TITLE
icons change

### ISSUE THREAD

**Issue by marchoso** [mapbox/geojson.io#650]
I trie to import a file gpx from the program Basecamp of Garmin, everythings its works but when it shows the icons, all are in the same color and symbol.
What can I do?

**Comment by morganherlocker** [comment]
What is your expectation here? This seems like reasonable behavior for geojson.io, considering its adherence to the [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0).

**Comment by sgillies** [comment]
Sorry @marchoso, Garmin icon import will not be supported.
