### ISSUE TITLE
Saved maps appear in monochrome

### ISSUE THREAD

**Issue by MoleValleyRamblers** [mapbox/geojson.io#652]
I have created a map using geojson.io and saved it as a gist. Although both Mapbox and OSM versions of the map appeared in colour when created, they are rendered in monochrome when opened in github. Not surprisingly I suppose, any links or embed scripts created within github also result in monochrome views of the map. 

How can I create shareable links to colour versions of my map ?

**Comment by sgillies** [comment]
@MoleValleyRamblers you can host your own map using Leaflet (for example) or upload your GeoJSON to a hosted service like Mapbox.
