### ISSUE TITLE
Best Way to Import Line Shapefiles 

### ISSUE THREAD

**Issue by GarrettRSmith** [mapbox/geojson.io#653]
Hello

I have converted a number of poly line Shapefiles into .csv files in and am trying to convert them to GEOJson files so that I can import them into an online mapping environment. When I try to either (1) open the files using the Open -> File method nothing shows up on the map and no code is present in the </> JSON window. Or (2) when I drag and drop the .csv file into the </> JSON window I do not get any GEOJson coding, instead I get the following:

TRAILNAME,SHAPELEN
Sanitas Valley,835.5762541

I did not have a problem with point Shapefiles, it just seems to be an issue with the poly line files. Is there something different that I need to do when preparing the line files before importing them into geojosn.io?

Thanks so much

**Comment by sgillies** [comment]
This app's CSV reader/writer is only capable of handling points. See the original author's notes in https://github.com/mapbox/geojson.io/issues/572. I recommend using a program like ogr2ogr to convert your shapefiles to GeoJSON.
