### ISSUE TITLE
Add a way to resize properties window

### ISSUE THREAD

**Issue by matejdro** [mapbox/geojson.io#654]
At the moment, properties window of a point is fixed size. This is a bit annoying if point has a lot of properties since user has to scroll:

![image](https://user-images.githubusercontent.com/507922/65747362-8f7c0f80-e101-11e9-9a50-9e004f7790f6.png)

It would be useful if there was a way to resize window (or have it resize automatically up to certain point) to show all properties at once.

**Comment by sgillies** [comment]
Please see the readme.
