### ISSUE TITLE
Nothing happened after file upload

### ISSUE THREAD

**Issue by RemiB961** [mapbox/geojson.io#656]
Hello

Sorry to bother you. I've uploaded my json file but nothing happened
Is there something i've missed ?

Open > File > myfile.json

**Comment by sgillies** [comment]
Ideally, the site would provide a helpful error message in this case, yes, but this will not be addressed soon. Meanwhile, double check your file for JSON syntax errors and GeoJSON conformance.

**Comment by RemiB961** [comment]
Hello

Thank you
The json is provided by Google Maps. Does it help ?

Le jeu. 3 oct. 2019 à 17:07, Sean Gillies <notifications@github.com> a
écrit :
