### ISSUE TITLE
Could not share: an error occurred: Requires authentication

### ISSUE THREAD

**Issue by brunetton** [mapbox/geojson.io#657]
Hi, 

I created a map after logged in and wanted to share it; but when clicking on "Share" button I have this message: "Could not share: an error occurred: Requires authentication"

I'm logged in (I can see my username on the top right of the screen).

What did I missed ?
Thanks

**Comment by The-Minh** [comment]
Same here

**Comment by anandpathak** [comment]
facing same issue 
<img width="1680" alt="Screenshot 2020-03-12 at 6 43 50 PM" src="https://user-images.githubusercontent.com/8623546/76525276-8d302680-6491-11ea-9abd-3261694e62b3.png">

**Comment by BaronAfutu** [comment]
I also faced this issue earlier but discovered a a way around that.

> **1. This involves first saving/pushing the draw feature feature into a GitHub repository (preferably _after_ adding any properties you plan to add).
> 2. Afterwards,  open the saved feature from GitHub using the open feature in geojson.io.
> 3. Then you can copy and share the URL to the page. (eg. http://geojson.io/#id=github:BaronAfutu/geosjson/blob/master/ugMaizeFarm.geojson&map=17/5.64291/-0.18201)**

You can find out more from this link;
https://github.com/mapbox/geojson.io/blob/gh-pages/API.md#map

To embed the map, check out this link
https://docs.github.com/en/github/managing-files-in-a-repository/mapping-geojson-files-on-github#embedding-your-map-elsewhere

**Comment by BaronAfutu** [comment]
You could also simply save the feature using the Gist option (_gist.github_) then you can have access to the option to **share or embed** the feature in Gist.
