### ISSUE TITLE
Enhancement Request: Import from Google MyMaps

### ISSUE THREAD

**Issue by carpiediem** [mapbox/geojson.io#659]
[Google MyMaps](https://www.google.com/maps/d/u/0/) has a KML download link, so it's already pretty easy to copy data from one to the other. But, you might want to consider making it even easier (just pasting in a URL like this: https://www.google.com/maps/d/u/0/viewer?mid=1mwyQdeN2QLa10fG2V82dKARKBnQ)

**Comment by sgillies** [comment]
We're sorry, this project is not accepting feature requests.
