### ISSUE TITLE
Pass multiple Points via CLI?

### ISSUE THREAD

**Issue by SeaDude** [mapbox/geojson.io#660]
I'm having trouble figuring out how to pass multiple URL-encoded points using the CLI syntax. Can someone put some eyes on this and tell me what I'm missing?
**Tried so far:**
`http://geojson.io/#data=data:application/json,` with the below added:

**Decoded**:
`{"type":"Point","coordinates":[47.5819689,-122.3869421]},"type":"Point","coordinates":[47.583717,-122.386024]}`
**Encoded** (using [this site](https://meyerweb.com/eric/tools/dencoder/)):
```
%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B47.5819689%2C-122.3869421%5D%7D%2C%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B47.583717%2C-122.386024%5D%7D
```
**Decoded**:
`{"type":"Point","coordinates":[[47.5819689,-122.3869421],[47.583717,-122.386024]]}`
**Encoded**:
```
%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B%5B47.5819689%2C-122.3869421%5D%2C%5B47.583717%2C-122.386024%5D%5D%7D
```

Thank yoU!

**Comment by bhousel** [comment]
2 things:

1.  You can use a type MultiPoint if you want multiple points.
2.  Coordinates in GeoJSON are `longitude,latitude`

This works:
```js
{
  "type": "MultiPoint",
  "coordinates": [
    [-122.3869421,47.5819689],
    [-122.386024,47.583717]
  ]
}
```

**Comment by SeaDude** [comment]
Thank you very, very much for the quick response @bhousel. I did not know about the `Multipoint` geotype. Trying now.

**Comment by SeaDude** [comment]
Bingo!
![image](https://user-images.githubusercontent.com/8636973/69678249-ea76a800-1059-11ea-89f1-25988aed8fc5.png)
