### ISSUE TITLE
Is Point or MultiPoint w/ Properties possible via CLI?

### ISSUE THREAD

**Issue by SeaDude** [mapbox/geojson.io#661]
How can I encode Properties for each point in a MultiPoint encoded URL?
**Example**:
**Encoding the following...**"
```
http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22MultiPoint%22%2C%22coordinates%22%3A%5B%5B-122.3858692%2C47.56452925%5D%2C%5B-122.387177%2C47.561455%5D%2C%5B-122.38679%2C47.562161%5D%2C%5B-122.386375%2C47.568764%5D%2C%5B-122.41095%2C47.577553%5D%2C%5B-122.3870841%2C47.5614664%5D%2C%5B-122.407364%2C47.577271%5D%2C%5B-122.386637%2C47.579173%5D%2C%5B-122.385849%2C47.562884%5D%2C%5B-122.4109498%2C47.5775947%5D%2C%5B-122.3869421%2C47.5819689%5D%2C%5B-122.40967%2C47.57968%5D%2C%5B-122.386024%2C47.583717%5D%2C%5B-122.386383%2C47.56538%5D%2C%5B-122.3847046%2C47.5826992%5D%5D%7D
```
**...results in**
![image](https://user-images.githubusercontent.com/8636973/69888804-a9250900-12a2-11ea-83cd-c375376d6033.png)

I need...
![image](https://user-images.githubusercontent.com/8636973/69888891-251f5100-12a3-11ea-8a22-4f338baa2ae5.png)

...but ideally sent as MultiPoint with each point having its own set of properties. 

1. Is this possible?
2. Is there a limit on number of points (AKA URL length)?

Thank you

**Comment by nauhc** [comment]
having the same question. is MultiPoint supported now?

**Comment by chriswhong** [comment]
> How can I encode Properties for each point in a MultiPoint encoded URL?

By definition a `MultiPoint` is multiple point geometries with a common set of properties.  If you want them each to have their own properties, you want a `FeatureCollection` of `Point` Features, not a `MultiPoint` Feature.

> having the same question. is MultiPoint supported now?

`MultiPoint` geometries are supported.

Closing this issue as not actionable.  

Related bugfix that will ensure the URL above is rendered properly: #783
