### ISSUE TITLE
geojson.io keeps ignoring my geojson

### ISSUE THREAD

**Issue by spierepf** [mapbox/geojson.io#663]
When I copy my geojson into geojson.io it is ignored without any kind of error message:

```
{"geometry":{"features":[{"geometry":{"coordinates":[1.0,2.0],"type":"Point"},"id":0,"type":"Feature"}],"type":"FeatureCollection"},"type":"Feature","properties":{"flightDate":1587513600,"routeString":"ROUTE_STRING","originAirportICAO":"ORIG","ident":"IDENT","destinationAirportICAO":"DEST","registration":"REG"}}
```

**Comment by spierepf** [comment]
Sorry, did not realize that all Features required properties entries. My bad. Would be a good error message.

**Comment by ingalls** [comment]
@spierepf Although your GeoJSON is perfectly valid, GeoJSON.io currently does not support nestled feature collections. (Nor does most software that supports GeoJSON). The problem with nestled FeatureCollections is that they are infinitely  nestable  which can result in a parsing nightmare.

```
{
  	"id": 0,
  	"type": "Feature",
    "properties": {
		"flightDate": 1587513600,
		"routeString": "ROUTE_STRING",
		"originAirportICAO": "ORIG",
		"ident": "IDENT",
		"destinationAirportICAO": "DEST",
		"registration": "REG"
	},
	"geometry": {
        "coordinates": [1.0, 2.0],
		"type": "Point"
	}
}
```

Should work just fine
