### ISSUE TITLE
OSM attribution missing

### ISSUE THREAD

**Issue by jomo** [mapbox/geojson.io#665]
Thanks for this useful tool!

Unfortunately, the OpenStreetMap attribution is missing when using the Mapbox layer, although that Map is clearly based on OSM data:

![Screenshot](https://user-images.githubusercontent.com/3585743/82104047-a49bc200-9715-11ea-9eee-904b3a900310.png)

**Comment by mikelmaron** [comment]
thanks for the ping on this @jomo, will fix
