### ISSUE TITLE
geojson.io zoom issue

### ISSUE THREAD

**Issue by ennui3000** [mapbox/geojson.io#666]
Hello!
We can't zoom in on map features in geojson.io as much as we used to.
Currently, maximum zoom level is set to 18 (indicated as map=18 in the url) which is quite inconvenient when we need to get a better look at small features on the map as in here:
![image (1)](https://user-images.githubusercontent.com/48246462/82185253-a0c49700-98f1-11ea-86c3-e0ad15118e00.png)
http://geojson.io/#data=data:text/x-url,https://api-eu-streets-review-production.mapbox.com/api/days/2020-05-12/views/encrypted/f099930a49749c9c55c22d346285458b.geojson&map=2/20.0/0.0
We were able to zoom much more closer before.

**Comment by sgillies** [comment]
@ennui3000 thanks for the report! This is now fixed by #667.
