### ISSUE TITLE
Using png/ image of map as a guide to redraw boundary lines in geojson

### ISSUE THREAD

**Issue by groupdigitalmedia** [mapbox/geojson.io#668]
Hi, is there a way that I can upload an image of my map that has all of its counties laid out already, import my image and use geojson.io to redraw that map? The mapbox from OpenStreetMap is not as detailed. I have to draw the co-ordinates in geojson by freehand, guessing where the boundary lines start and end.

Can someone assist?
Thanks
Andrew
![MAP-ELECTIONS-2010-MAP-LABEL-background](https://user-images.githubusercontent.com/65859740/82869740-c73f8f00-9efc-11ea-9447-dd23d4d81da8.png)

**Comment by sgillies** [comment]
No, that kind of application is not what geojson.io is about. You way want to take a look at https://mapwarper.net/.
