### ISSUE TITLE
Quick question about \n characters.

### ISSUE THREAD

**Issue by lance-weaver** [mapbox/geojson.io#669]
I'm trying to get "coordinates": output to NOT be on new lines.  Putting each long/lat pair on a new line makes the output with polygons/polylines really verbose and hard to copy/paste to use in other applications.  
For instance:
          [[
            long,
            lat
          ],
          [
            long,
            lat
          ],]

makes a much smaller file if its [[long,lat],[long,lat]]

Anyone know where in the site.js file this behavior is dictated?  I'd love to be able to change, it... if only just on my own personal version.

**Comment by sgillies** [comment]
@lance-weaver If I'm not mistaken (I'm not the author, only semi-maintainer), the implementation is here: https://github.com/mapbox/geojson.io/blob/0b7338d929a29897e747e1411c17861bcb28015c/src/panel/json.js#L50. It's `JSON.stringify()` with a `space` parameter of 2, which forces coordinate values onto new lines. Good luck!
