### ISSUE TITLE
Mouse wheel scroll Toggle button

### ISSUE THREAD

**Issue by anthonybudd** [mapbox/geojson.io#671]
I love geojson.io but it's practically unusable with a MagicMouse and inertial scrolling enabled.

Could there be a toggle button to temperately disable zoom with the mouse wheel?

**Comment by anthonybudd** [comment]
Any word on this?

**Comment by chriswhong** [comment]
Closing as stale, though would love to hear if this is still of concern after the recent switch to mapbox-gl-js instead of mapbox.js/leaflet.
