### ISSUE TITLE
Lat Long vs Long Lat

### ISSUE THREAD

**Issue by mark-steven-au** [mapbox/geojson.io#672]
Would be nice if you could have the option to flip the co-ordinates so that it maps Lat Long vs Long Lat coordinates.
Program I am using requires them the other way around so requires manually switching them.
Being able to switch would be great.

**Comment by sgillies** [comment]
Sorry, but we're not accepting requests for new features. Besides, geojson.io is intended to promote the use of standard GeoJSON (among other formats) and won't muddy the waters, so to speak.
