### ISSUE TITLE
About edit point and move polygon in edit mode

### ISSUE THREAD

**Issue by lystormenvoy** [mapbox/geojson.io#675]
I often use geojson.io to draw a map of a county.
I draw the town or street area of the county.
At first I draw the polygon area not very accurately.
Then I need to edit the polygon.
Most of time I just need to adjust the point slightly to make the boundary of one area touch nearby area's boundary. Make they seamless.
But sometimes when I want to drag the point, I found I drag the polygon actually. That make me have to cancel my edit.
  
  ----

**So I hope there will have a switch to lock the edit of move polygon. When I turn it on, I just can move the point and can not move the whole polygon.**

**Or just let the cursor show with different shape between the cursor hover on point and hover on polygon in edit mode.
So that I can know if is a point I was editing.**

**Comment by sgillies** [comment]
@lystormenvoy I see what you mean. I'm sorry to say that we have no plans to add such an editing feature. There are tools to mathematically "snap" shapes together to make them very seamless and I recommend trying one of these.

**Comment by lystormenvoy** [comment]
> @lystormenvoy I see what you mean. I'm sorry to say that we have no plans to add such an editing feature. There are tools to mathematically "snap" shapes together to make them very seamless and I recommend trying one of these.

Could you tell me the names of these tools?

Or I just suggest to make a different cursor style to make me know what I am dragging directly.
