### ISSUE TITLE
Unacceptable authorization requirements

### ISSUE THREAD

**Issue by DarinMacRae** [mapbox/geojson.io#677]
It should never be necessary to require a user for these permissions just to authenticate.

![image](https://user-images.githubusercontent.com/3474753/103035945-58bbc180-451d-11eb-8980-39f89705b47a.png)

Please trim this down or at least separate authentication (which is required for sharing) from the ability to read and write to GitHub repos and Gists. These two things should not be tightly linked.

**Comment by grzniuk** [comment]
That's enough to put me off too i'm afraid.

**Comment by chriswhong** [comment]
Auth is being removed for the time being as of https://github.com/mapbox/geojson.io/pull/703, closing.
