### ISSUE TITLE
Upgrade to use latest Leafletjs?

### ISSUE THREAD

**Issue by mrummuka** [mapbox/geojson.io#682]
Leafletjs has now v1.7.1 published (https://leafletjs.com/reference-versions.html) and there have been quite a many changes since 0.7.x which I believe is the currently used version. Please consider bumping up leafletjs to latest version.

**Comment by muuvmuuv** [comment]
I support this! It seems the style props aren't longer correctly named.

**Comment by chriswhong** [comment]
We are moving to mapboxgl in https://github.com/mapbox/geojson.io/pull/703, closing.
