### ISSUE TITLE
Why are you asking for so many github privileges when trying to login?

### ISSUE THREAD

**Issue by defiantgoat** [mapbox/geojson.io#683]
These seem a bit excessive.

Gists
Read and write access
This application will be able to read and write your public and secret gists.

Learn more
Repositories
Public and private
This application will be able to read and write all public and private repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
Collaboration invites

**Comment by sgillies** [comment]
It's a known issue #677. For what it's worth, the code of concern hasn't changed in ~5 years. The site isn't asking for any more privileges today.
