### ISSUE TITLE
"Share" giving an "requires authentication" while logged into github

### ISSUE THREAD

**Issue by fgregg** [mapbox/geojson.io#684]
For a geojson file that is saved to a gist, if i click on the share button I get a "requires authentication" error message. I believe this is because the underlying github API request is not including an authorization token in its header.

![Screenshot_2021-04-07 geojson io](https://user-images.githubusercontent.com/536941/113872420-dd0b1b00-9781-11eb-8ce0-4a71af580952.png)

I'm logged into github, and I can create and save files to a gist without problem.

Opening up the network calls, there's a 401 response to the github api. The request headers do not include an authorization token as the calls to save the gist do.

```bash
POST /gists HTTP/1.1
Host: api.github.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0
Accept: application/json,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: text/plain;charset=UTF-8
Content-Length: 3188
Origin: http://geojson.io
Connection: keep-alive
Referer: http://geojson.io/
```

**Comment by chriswhong** [comment]
Auth is being removed for the time being in https://github.com/mapbox/geojson.io/pull/703, closing as no longer relevant
