### ISSUE TITLE
Allow editing on mobile

### ISSUE THREAD

**Issue by panchicore** [mapbox/geojson.io#687]
Awesome utility, we are using it as part of a data collection for incidents that involve markers, lines, and areas, we just need to copy/paste the JSON to make the backend work. But when we want to use it on android phones, even activating the "request desktop version", it won't allow selecting anything on the map, when the marker icon is selected, it displays the "cancel" tooltip but it won't be possible to pin it on the map to generate the geojson text.

**Comment by chriswhong** [comment]
This should be possible after #779 is in.

**Comment by chriswhong** [comment]
Closed as of #779
