### ISSUE TITLE
Allow editing geojson in the (right) sidebar

### ISSUE THREAD

**Issue by remster** [mapbox/geojson.io#691]
Your help page says:
"If you have data, like a KML, GeoJSON, or CSV file, just drag & drop it onto the page or click 'Open' and 'File' - your data should appear on the map!"

I do have the data, but not in a file - there is a handy editor for the geojson, but editing (pasting to it) doesn't change the map. Why not? Bit frustrating. The UI just begs to be used that way

**Comment by csytsma** [comment]
@remster I've been successful at pasting my GeoJSON into the JSON tab on the right. Once I paste it, it instantly appears on the left.  Look for a red block on the left side of the JSON field, where it will tell you if there's an error.

**Comment by chriswhong** [comment]
Closing, please add some sample data so we can reproduce the error.
