### ISSUE TITLE
Authentication Fail 2022

### ISSUE THREAD

**Issue by Abdulrahman-Awad21** [mapbox/geojson.io#693]
![image](https://user-images.githubusercontent.com/93622980/174593122-1ab2a2fd-8c0d-4c8c-aab2-2eb46cdbc58e.png)

**Comment by devleaks** [comment]
I don't know if it is linked, but I can no longer login to github. No error message nothing.
No error on console. Tried with different browsers.
Thank you for your help.

**Comment by fedderw** [comment]
I'm having the same problem. I can't use the github integration without authenticating, but I can't seem to find a prompt or instructions.

**Comment by chriswhong** [comment]
Authentication will be removed as of https://github.com/mapbox/geojson.io/pull/703, closing.
