### ISSUE TITLE
KML file - style definition incompatibility

### ISSUE THREAD

**Issue by d-danger** [mapbox/geojson.io#695]
When exporting to KML - the style data is saved incorrectly.  For example:
```
<ExtendedData>
<Data name="stroke"><value>#ff0000</value></Data>
<Data name="stroke-width"><value>2</value></Data>
<Data name="stroke-opacity"><value>1</value></Data>
</ExtendedData>
```

When opening a KML file - the valid KML style tags are ignored.  For example:
```
<Style>
<LineStyle>
<color>ff0000ff</color>
<width>2</width>
</LineStyle>
</Style>
```

Using [togeojson](https://mapbox.github.io/togeojson/) and then pasting the GeoJSON is a workaround.

**Comment by chriswhong** [comment]
Hi, we will no longer support styling as of https://github.com/mapbox/geojson.io/pull/703, closing as no longer relevant
