### ISSUE TITLE
International dateline issue 

### ISSUE THREAD

**Issue by cjerv** [mapbox/geojson.io#696]
How to fix this issue with the data when uploading a KML file to geojson, and having the track glitch at the international dateline.

See image

![Screenshot 2022-08-05 at 15 40 59](https://user-images.githubusercontent.com/93710516/183028183-f12cef95-9bf3-4471-ac34-48145ff0ebac.jpg)

The data came from [Flight Radar 24](https://www.flightradar24.com/data/flights/cx97)

When imported into Google Earth the data maps like this 
![Screenshot 2022-08-05 at 15 50 26](https://user-images.githubusercontent.com/93710516/183029469-2cbd8bc7-6659-47dd-8be0-ea95dfe22474.jpg)

I wish to use this geojson file in mapbox, so this current setup isn't going to work

**Comment by cjerv** [comment]
The data came from a Flight Radar 24 KML download file of a flight from Anchorage to Hong Kong.

**Comment by cjerv** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/line-across-180th-meridian/

Found solution

**Comment by cjerv** [comment]
![Screenshot 2022-08-06 at 17 47 59](https://user-images.githubusercontent.com/93710516/183243803-0729dccd-6c2c-476b-85d3-2a44bfc789a2.jpg)

Unsolved.  
Any tips?

**Comment by chriswhong** [comment]
Closing as this is a data issue that won't be addressed in geojson.io
