### ISSUE TITLE
Custom Topojson display different between converted Geojson and PowerBI

### ISSUE THREAD

**Issue by Meltingmon** [mapbox/geojson.io#700]
I am trying to convert the topojson and combine floor plans into one topojson to use in PowerBI. But the coverted geojson displayed with extra geometry. Any idea why and how to fix it? 
![image](https://user-images.githubusercontent.com/114445574/192385477-18c4dae7-5e63-460b-9396-d5d60c6d9e11.png)

**Comment by chriswhong** [comment]
Closing as this seems like an issue with your input data.  Feel free to re-open and include a snippet of data.
