### ISSUE TITLE
geojson missing attributes

### ISSUE THREAD

**Issue by BennyTSB** [mapbox/geojson.io#705]
I'm trying to use data for a symbol map I'm making on datawrapper, problem is the geoJSON file comes up with an error saying, 'Every map region must have at least one named property.', and the topoJSON comes up with an error saying, 'Uploaded file is not in JSON format.' I tested both file types along with Shapefile files and all 3 come up with an issue saying the layer is 'missing attribute data'. Is there any glaring, obvious issues with what I've done?

**Comment by chriswhong** [comment]
Can you provide a sample of the data?

**Comment by BennyTSB** [comment]
> Can you provide a sample of the data?

I can't link the file as it's not supported but this was the raw paste I got

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-0.9064579010009766,50.7750073425164],[-0.8844852447509765,50.77517017178909],[-0.8852577209472656,50.78225269649333],[-0.9052133560180664,50.78219842835159],[-0.9064579010009766,50.7750073425164]]]}}]}

**Comment by chriswhong** [comment]
This geojson is valid, it sounds like the errors you're getting are from datawrapper.  Perhaps they have stronger opinions about what needs to be included in a geojson file.

**Comment by chriswhong** [comment]
Closing as this isn't an issue with geojson.io
