### ISSUE TITLE
Restore simplestyle colors

### ISSUE THREAD

**Issue by anoop-kn** [mapbox/geojson.io#712]
We lost stroke colors in the latest update of the site. None of our stroke colors are showing up.

        "stroke": "#9FFB66",

**Comment by camerondavison** [comment]
I was using the "fill" property like this to color different collections.

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {        
        "fill": "#1f77b4"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.98973352215812,
              36.29617693859247
            ],
```

**Comment by rreusser** [comment]
Not because I think it should necessarily be supported, but just tracking different permutations, GaiaGPS, for one, includes in exported geojson properties:

```json
      "type": "Feature",
      "properties": {
        "color": "#00A478",
        "hexcolor": "#00A478",
        ...
      },
      "style": {
        "stroke": "#00A478"
      },
      "geometry": {
        "type": "MultiLineString",
```

**Comment by anoop-kn** [comment]
We use it to draw wour vehicle paths and use stroke to color certain road segments to indicate stops etc. Can we access the older version somewhere? I tried to checkout an older commit from last year but had node install problems with contextify package.

**Comment by maxahlberg** [comment]
Ye as @anoop-kn is indicating. We are using it to display different properties of the segments in a geojson. Like if we have been driving a certain direction or speed. If we shall stop or not. It gives a visual representation of other properties.

**Comment by chriswhong** [comment]
@anoop-kn @anoop-kn FYI you can run any earlier version by rolling back to a commit and running a live server, there's no need to install dependencies and mess with node unless you're making changes.  

I'll look into what it will take to bring this functionality back in.

**Comment by stevage** [comment]
FWIW @rreusser, an extra property like `style` at the top level is perfectly acceptable in the GeoJSON spec. Arguably, it's a better way of separating style properties out from data properties, although I don't think I've seen any other software do it that way.

**Comment by jiaqian117** [comment]
I meet same issue, here's my code, and I want to show different colors, I use "marker-color",  but suddenly it doesn't work, what should I do?
`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          103.959564,
          1.377149
        ]
      },
      "properties": {
        "marker-color": "#ff2600"
      }
    }
}`

**Comment by madbeyk** [comment]
http://geojson.io/#id=gist:madbeyk/02a0c60831933463e40a190018377caa&map=10/50.7760/14.9867
used to be color map like this ...
![lbk_ms_future](https://user-images.githubusercontent.com/2467188/196897416-90098c35-4f57-42d7-94fa-09a73d4b33e4.jpg)
@chriswhong  thanks for reverting these features back ...

**Comment by marcbuettner** [comment]
I used geojson.io to draw areas and lines and pass them to Datawrapper.de, via copy&paste.
The areas need an independent color, so that they are recognized there as individual elements.

Thanks for bringing back the function, but can you also add the colorpicker back?

**Comment by chriswhong** [comment]
Hi, we just merged a small change to restore styling based on simplesstyle-spec properties.  We would love your feedback on if it meets your needs.

**Comment by anoop-kn** [comment]
yes, the team confirmed it works. Thanks for the quick fix.

**Comment by camerondavison** [comment]
i agree 🎉 thanks for the quick fix. this looks great.
