### ISSUE TITLE
Point geometry is not being displayed when part of GeometryCollection

### ISSUE THREAD

**Issue by jventuri2** [mapbox/geojson.io#722]
When I try to render a GeometryCollection that contains a single Point and 3 Polygons, the Polygons are being displayed correctly but the Point does not.  This worked a couple days ago.  

I have validated the GeoJSON is correct by displaying at geojsonlint. Attached is the sample FeatureCollection containing the GeometryCollection.

[GeometryCollectionWithPoint.zip](https://github.com/mapbox/geojson.io/files/9832906/GeometryCollectionWithPoint.zip)

**Comment by chriswhong** [comment]
There are several older issues related to Multi features and GeometryCollections.  At some point we will need to figure out if less common variations of Geojson can/should be supported.
