### ISSUE TITLE
Race Condition: data update prior to map load

### ISSUE THREAD

**Issue by chriswhong** [mapbox/geojson.io#728]
When loading geojson from a URL parameter such as with a github file, it's possible for `context.data` to be set prior to the map load.  

There is a check for `map.isStyleLoaded()` before updating the map data.  If it runs too soon, the user will end up with properly-loaded geojson in the data editor pane, but nothing on the map.

Example: `https://geojson.io/#id=github:ebrelsford/geojson-examples/blob/master/brooklyn.geojson`

**Comment by wboykinm** [comment]
Behavior note - subsequent redraws, such as on baselayer switch, will show the late-loaded features.
