### ISSUE TITLE
External file loaded with URL parameters and valid CORS no longer works, displays error

### ISSUE THREAD

**Issue by kevinmilner** [mapbox/geojson.io#741]
Hello, I am encountering a new issue today, maybe related to the redesign. External files are not working, even though they load fine when opening them locally and have valid CORS headers. These same files worked previously via CORS, and nothing has changed on the server configuration.

[Here is an example link that used to work.](http://geojson.io/#data=data:text/x-url,http%3A%2F%2Fopensha.usc.edu%2Fftp%2Fkmilner%2Fmarkdown%2Fbatch_inversions%2Fnshm23-draft-latest%2Fbranch_averaged_gridded%2Fresources%2Fconn_clusters.geojson)

Instead of (eventually, it's a large file) opening, it shows this error message:

`Could not load external file. External files must be served with CORS and be valid GeoJSON.`

As mentioned, the file is served with CORS, [see test here](https://cors-test.codehappy.dev/?url=http%3A%2F%2Fopensha.usc.edu%2Fftp%2Fkmilner%2Fmarkdown%2Fbatch_inversions%2Fnshm23-draft-latest%2Fbranch_averaged_gridded%2Fresources%2Fconn_clusters.geojson&method=get).

[Here is a direct link to download the file](http://opensha.usc.edu/ftp/kmilner/markdown/batch_inversions/nshm23-draft-latest/branch_averaged_gridded/resources/conn_clusters.geojson) to test loading it locally (via the "Open" button on geojson.io).

**Comment by chriswhong** [comment]
<img width="792" alt="geojson_io_and_geojson_io" src="https://user-images.githubusercontent.com/1833820/197847061-5faefe99-18e6-4819-8edc-abb9b7968bf8.png">

Looks like trying to load that file over https gives an invalid cert error.  Is it possible to update the SSL on that server?

geojson.io is served by github pages and we recently enabled "enforce https".  I think this is a `wontfix` but we should make sure to show a more appropriate error message and include something about https in the documentation for the `data:text` URL parameter

**Comment by kevinmilner** [comment]
Good catch @chriswhong , that's it. Looks like the SSL cert expired over the weekend. Yeah a more useful error message would be great for other people who encounter this issue in the future

**Comment by kevinmilner** [comment]
@chriswhong here's a new wrinkle. The SSL cert has been fixed, but the link doesn't work unless you explicitly specify https, which seeps to be a new behavior. Is that an intentional change on your end?

HTTP (does not work, but used to): http://geojson.io/#data=data:text/x-url,http%3A%2F%2Fopensha.usc.edu%2Fftp%2Fkmilner%2Fmarkdown%2Fbatch_inversions%2Fnshm23-draft-latest%2Fbranch_averaged_gridded%2Fresources%2Fconn_clusters.geojson

HTTPS (now works after updated certificate): http://geojson.io/#data=data:text/x-url,https%3A%2F%2Fopensha.usc.edu%2Fftp%2Fkmilner%2Fmarkdown%2Fbatch_inversions%2Fnshm23-draft-latest%2Fbranch_averaged_gridded%2Fresources%2Fconn_clusters.geojson

**Comment by chriswhong** [comment]
Hi, glad this is working again!  I've never seen data like this, what are we looking at?

I think the right flow here is just to show an appropriate message like "Data loaded from an external geojson file must be served over https" and adding a note about this in the help section where we describe this API. I wouldn't want to add logic to try to modify the url, we should just enforce the rule that https is what works and show a useful notice when it is not provided.

<img width="867" alt="Cursor_and_geojson_io" src="https://user-images.githubusercontent.com/1833820/198684045-83841694-2725-4e5b-b977-ac935448dd69.png">

**Comment by kevinmilner** [comment]
Yes that error message would be a big improvement!

The data plotted are faults in the Western US, we're using your tool to visualize preliminary results as we build the next national seismic hazard model. Thanks for such a great tool!

**Comment by chriswhong** [comment]
Closing, the improved error message will be addressed in #742
