### ISSUE TITLE
Restore functionality of Editing Geometries

### ISSUE THREAD

**Issue by zaitseff** [mapbox/geojson.io#749]
Thank you for working on Geojson.io.  However, I am finding the new interface for editing geometries to be much worse than what was there previously.  Could those now-gone features be restored / reintroduced?

In particular:

* The DEL key no longer works for removing a vertex / point -- you have to move the mouse to the Delete icon on the top right hand side.  I suspect all shortcut keys are now gone: it would be good to restore all of them.
* Moving a point now requires selecting it first with the mouse: double the number of clicks now needed to edit a path.
* In Edit Geometries mode, differentiating between vertices on a line and a Point (marker) is very difficult, unlike the previous functionality in which points still retained their look of map markers.
* Hovering over a vertex does _not_ change the mouse cursor from the usual Hand cursor.

**Comment by chriswhong** [comment]
Hi, thanks for bringing these concerns to our attention.

> The DEL key no longer works for removing a vertex / point -- you have to move the mouse to the Delete icon on the top right hand side. I suspect all shortcut keys are now gone: it would be good to restore all of them.

I'm not familiar with how these keyboard shortcuts worked under Leaflet Draw, can you provide some more information on the ideal flow you're looking for for deleting a vertex with the delete key?  Are you talking about deleting the last vertex while drawing, or editing an already drawn feature and deleting a vertex?  I loaded an earlier version of geojson.io but I'm on a Mac and don't have a DEL key.  Even if I had one, I don't think there is any concept of selecting a vertex when editing, so how would it know which vertex you want to delete?

> Moving a point now requires selecting it first with the mouse: double the number of clicks now needed to edit a path. 

> In Edit Geometries mode, differentiating between vertices on a line and a Point (marker) is very difficult, unlike the previous functionality in which points still retained their look of map markers.

Both of these changes come from the switch to `mapbox-gl-draw` and would take some customization to restore.

> Hovering over a vertex does not change the mouse cursor from the usual Hand cursor.

I am not seeing this, the cursor turns into a "move" cursor when hovering a vertex in edit mode.  Can you please confirm?
![image](https://user-images.githubusercontent.com/1833820/198742225-39a03d0f-4bd4-4361-884e-dbf71083bef1.png)

**Comment by zaitseff** [comment]
Thanks for your quick response, @chriswhong!  Is there information about how to load the old site for myself?  Then I could provide a step-by-step procedure of how the old way worked vs the current way.

I use geojson.io to import KML files from Google Maps, or GPX files from Garmin devices, then edit the tracks thus imported.  Thus by "deleting a vortex" I am editing an already drawn feature.  The new workflow is "select vortex with a mouse click, move mouse to delete icon and click, then move back to next vortex to delete or move".  It used to be something like "select vortex with mouse click, press Delete, move mouse slightly to next vortex".

I appreciate changes would need to be made due to `mapbox-gl-draw` being used, but I think it is worth considering how the user experience (UX) might be improved thereby.  It might be enough to include shortcut keys.

> > Hovering over a vertex does not change the mouse cursor from the usual Hand cursor.
>
> I am not seeing this, the cursor turns into a "move" cursor when hovering a vertex in edit mode. Can you please confirm?

Using Firefox 106.0 under Linux, hovering over a vortex that is already selected does indeed change the cursor.  Hovering over a vortex _not_ selected, I've just discovered, also changes the cursor.  But hovering over what _looks like_ a vortex (but is in fact the mid-point of a line segment) does _not_ change the cursor.  So my initial comment was wrong: the problem is that vertices and mid-points look the same...

Also, part of the small frustration is that moving the entire multi-point line instead of a single vertex is way too easy...  I then have to cancel all edits to get the line back to where it was.  Perhaps there is a better way to do things.  But I am willing to work with you to see if any of these issues can be resolved!  I'll see if I can glance at the JavaScript as well -- although JS is not my programming language of choice :-)

**Comment by fedderw** [comment]
> Thanks for your quick response, @chriswhong! Is there information about how to load the old site for myself? Then I could provide a step-by-step procedure of how the old way worked vs the current way.
> 

I would also appreciate this! Currently very little works. Clicking on the geometry usually doesn't bring up the properties editor, and then you can't edit the colors with the dropper when it does

**Comment by chriswhong** [comment]
You can roll back to any commit prior to October 13th, 2022 and run a local server, you'll be able to use the app as it was prior to the Mapbox GL JS changes.  This is the last commit prior to the upgrade to Mapbox GL: https://github.com/mapbox/geojson.io/commit/ffde5cc5c00c039ea1f3b7a5fbf0b3f83136130a

**Comment by chriswhong** [comment]
@zaitseff I just pushed a branch which adds a keybinding for the delete key when editing.  Pressing delete will do the same thing as clicking the trash icon.

Would you be able to pull down this branch and test the functionality?

**Comment by chriswhong** [comment]
FYI, the delete key shortcut is restored as of https://github.com/mapbox/geojson.io/pull/755.  We also added some keyboard shortcuts for the draw tools.

**Comment by chriswhong** [comment]
Hi, we have addressed some but not all of the issues raised here.  Closing this, but if you would like to promote the other issues (Moving a point now requires selecting it first with the mouse), (In Edit Geometries mode, differentiating between vertices on a line and a Point (marker) is very difficult) please open a new issue for each one.
