### ISSUE TITLE
Could you  add some function ？

### ISSUE THREAD

**Issue by anders86755** [mapbox/geojson.io#759]
Could you  add some function ？
1. Line splitting and merging
2. Enhancements to delete functionality：Because the delete operation is a frequently used function, I hope to use shortcut keys to delete elements to improve efficiency； Also I hope to have a box selection tool to select elements in batches and delete them。

**Comment by chriswhong** [comment]
Hi, thanks for adding these suggestions, I've created a new issue for number 1, Line Splitting and Merging (and extending) #760

FYI using the delete key to delete a vertex was added recently, please give it a try and let us know if it meets your needs.

Also FYI, it's possible to select features in draw mode using a box by holding down shift and dragging the map.

Closing, please add more discussion to #760 if you have ideas or examples for how those tools might work.
