### ISSUE TITLE
Inefficiency in delegate.js

### ISSUE THREAD

**Issue by chriswhong** [mapbox/geojson.io#770]
`delegate.js` requires mapboxgl only to check `mapboxgl.supported()` and redirect the browser to `/unsupported.html`.

Since delegate.js is not part of the main build (site.js), the browser ends up downloading mapboxgl twice.  

I'm not sure why `delegate.js` needs to be its own file and why we can't just do these redirects in the main js bundle.  

We may also want to think bigger about whether `mobile.html` and `unsupported.html` are even necessary (can we make the main app more mobile-friendly/ show an unsupported message in place of the map)

**Comment by mourner** [comment]
As a quick fix, you can just replace `mapbox-gl` there with `@mapbox/mapbox-gl-supported`.

**Comment by chriswhong** [comment]
Perfect!  Thanks for bringing this to our attention
