### ISSUE TITLE
Requires authentication on attempt of saving geojson

### ISSUE THREAD

**Issue by andsimakov** [mapbox/geojson.io#778]
As far as I remember the feature of saving geojson as a gist was available. I was authorized to my Github and when I pressed Cmd-S (macOS), geojson was saved as a gist, I found a lot of them in my account. Now when I press the combination, I just get "Requires authentication" message in the map window and nothing happens. I don't see any controls in geojson.io browser tab to be authenticated.

**Comment by chriswhong** [comment]
Hi, [authentication was removed](https://github.com/mapbox/geojson.io/pull/703) from geojson.io recently, as it was not working consistently.  We would like to restore it someday, but don't have a timeline on implementation.
