### ISSUE TITLE
Make it more difficult to move an entire geometry

### ISSUE THREAD

**Issue by fedderw** [mapbox/geojson.io#780]
I would like to create a new issue for this because it's really a workflow hindrance.

> Also, part of the small frustration is that moving the entire multi-point line instead of a single vertex is way too easy...  I then have to cancel all edits to get the line back to where it was.  Perhaps there is a better way to do things.  

_Originally posted by @zaitseff in https://github.com/mapbox/geojson.io/issues/749#issuecomment-1295633588_
      
 I'd say I end up accidentally moving the entire feature collection over, and have to throw out my edits about 1/3 to 1/2 of the time I'm in there. 

It should be much harder to do that by accident, but maybe this is an issue for `mapbox-gl`, rather than geojson.io!

**Comment by chriswhong** [comment]
I think the right approach here would be to add a modifier key for dragging a feature.  The user still needs to be able to select entire features so they can be deleted.  We can intercept the drag event and only send it to mapbox-gl-draw if the user is holding down the modifeir key.
