### ISSUE TITLE
Change default line color for satellite view

### ISSUE THREAD

**Issue by fedderw** [mapbox/geojson.io#781]
The current default is really hard to see close up, since they are about the color and width of the streets. 

As an example, I dragged the Miami Metromover geojson lines over on top of Baltimore. Could you tell where it is?

![image](https://user-images.githubusercontent.com/16396180/201541296-40f999d7-4c63-42ba-9667-f13d25e6eba1.png)

Here is the black-and-white
![image](https://user-images.githubusercontent.com/16396180/201541316-0388b503-6ad8-4c5f-92b2-5d39862f8446.png)

**Comment by DJFriar** [comment]
@chriswhong I went ahead and submitted [PR 794](https://github.com/mapbox/geojson.io/pull/794) for this issue/enhancement.

I did try to link it to this issue but it appears I either didn't do it right or there is some permission required that I don't have. Apologies if it was my error, this is actually my first contribution to an open source project.
