### ISSUE TITLE
Display point geometry when passed using URL params

### ISSUE THREAD

**Issue by mappingvermont** [mapbox/geojson.io#788]
hey @chriswhong - thanks so much for giving this repository some love! So happy to see all the new changes 👏 👏 👏 

I use the [geojsonio-cli](https://github.com/mapbox/geojsonio-cli/) a fair amount in my work- it's a little CLI that passes geojson to geojson.io for visualization. I use this most often with point geometries to double check where things are. Here's an example URL generated by the CLI:

http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22Feature%22%2C%22geometry%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B3.7080748129414016%2C51.53710507194907%5D%7D%2C%22properties%22%3Anull%7D

This passes this geojson to geojson.io:
```json
{"type":"Feature","geometry":{"type":"Point","coordinates":[3.7080748129414016,51.53710507194907]},"properties":null}
```

This used to display a point marker on the map, but now seems to just zoom to the point itself. Any chance you could bring this feature back to display a point when passed via the URL? Or is there a new way for me to achieve this functionality?

Here's a screenshot of the current output for the link above. The JSON is visible in the JSON panel, but no marker on the map:

![image](https://user-images.githubusercontent.com/5845672/202530108-0cdde47b-8424-4f5b-8419-299f66c48052.png)

Thank you!

**Comment by chriswhong** [comment]
This is a known bug when properties is `null`.  (#610)

Should be an easy fix, I'll take a look.

**Comment by mappingvermont** [comment]
Amazing- thanks @chriswhong!

**Comment by mappingvermont** [comment]
Gorgeous! Thanks so much @chriswhong 🙏 💯 🙌 

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/5845672/203433153-9a559a30-4f17-4620-8394-15c41b2948aa.png">
