### ISSUE TITLE
It is not possible to download files in kml format 

### ISSUE THREAD

**Issue by felipedesouza555** [mapbox/geojson.io#789]
It is not possible to download files in kml format 

State with more than one machine, you click on the kml option and nothing happens

Google chormer, safari

**Comment by chriswhong** [comment]
I'm seeing kml exports working after drawing a feature.  Are loading external data and then exporting?  If so, can you share the geojson here?

Do you have any errors in the console?

**Comment by chriswhong** [comment]
Closing, if you are still seeing this issue, please provide a reproducible case.
