### ISSUE TITLE
Large IDs and (even properties!) appear to be changed as part of normalization to FC

### ISSUE THREAD

**Issue by jerstlouis** [mapbox/geojson.io#791]
e.g.,

https://maps.gnosis.earth/ogcapi/collections/osm:ottawa:buildings/items/2305843009223239036.json

vs.

https://geojson.io/#data=data:text/x-url,https://maps.gnosis.earth/ogcapi/collections/osm:ottawa:buildings/items/2305843009223239036.json

changes the ID from 2305843009223239036 to 2305843009223239000, and even changes the internal `feature::id` property to that new ID!

**Comment by chriswhong** [comment]
Good one!  This is almost surely related to the fact that this integer is larger than the maximum safe integer in javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

Did this work prior to the normalization to FeatureCollection? I assume it's not possible to store these values as strings instead these very large integers?

**Comment by jerstlouis** [comment]
@chriswhong I believe it did work just fine prior to this new stuff, yes.

Strings are horrible. Integers FTW.

**Comment by chriswhong** [comment]
Closing as there's nothing we can take action on to support these very large integers.

**Comment by jerstlouis** [comment]
@chriswhong Is this a limitation of the new Mapbox library?
The proper solution would be to use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for integer IDs.

**Comment by chriswhong** [comment]
This occurs as soon as we run `JSON.parse()` on data that has large integers in it. I rolled back to a commit from months ago before we brought in mapboxgl and the same thing was happening.

I did notice that the code editor retained the large integer from the geojson string on first load, but the data parsed into memory contained the modified values.  As soon as you make an edit, it updates the code editor to reflect the modified values.

**Comment by jerstlouis** [comment]
@chriswhong Can this be done:

```js
const reviver = (key, value) => key === "big" ? BigInt(value) : value;

const payload = '{"number":1,"big":"18014398509481982"}';
const parsed = JSON.parse(payload, reviver);

console.log(parsed);
```
as [explained here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json).
