### ISSUE TITLE
Regression: polygon icon loads rectangle

### ISSUE THREAD

**Issue by wboykinm** [mapbox/geojson.io#801]
<img width="474" alt="Screen Shot 2022-11-29 at 9 43 37 AM" src="https://user-images.githubusercontent.com/735463/204561168-c510170c-503a-48a2-858e-63dd3fe6f760.png">

Not clear to me where this would have been introduced if not in the rollup add, though [the CSS shows no substantive change](https://github.com/mapbox/geojson.io/commit/d62731f0426a9a33369ab24c736053674f4859e0#diff-640076e43ea277556b11bc62ec846a740ad8301eb7e730f0b77fe76efaffb0ffR550) (Doublequotes 🤷 ), and the [`polygon.svg` file](https://github.com/mapbox/geojson.io/blob/main/img/polygon.svg) still contains the correct icon.

**Comment by chriswhong** [comment]
This was probably introduced in #798 due to the order that css is included
https://github.com/mapbox/geojson.io/blob/main/src/index.js#L15-L25

I have a vague memory of moving the mapbox css to the end for some other reason, but can't remember what that was.
