### ISSUE TITLE
API to programmatically access map / data?

### ISSUE THREAD

**Issue by mrummuka** [mapbox/geojson.io#806]
Hi,

first of all - I'm very happy that the development of geojson.io has been continued. However, as I understand the underlying architecture has been changed from leaflet to mapbox, I have few question related to rather specific use case of mine.

Previously, I had written a tampermonkey add-on to enable few additional functionality automatically/programmatically on top of geojson.io, which more or less relied on either using api.data.mergeFeatures to append programmatically generated new geojson features both to data object as well as on map or map to add features (e.g. L.circle) or modify manually created features (e.g.  modify key-value pairs for all features).

More specifically, I had few use cases which consisted of  
(1) button asking user entering coordinates which then added a new point feature to specific location (ie generated appropriate geojson point + appended that on map)
(2) button to ask a set of coordinates from user which then generated set of point features to data object + appended those on map
(3) assigning specific key-value pair to all geojson features
(4) programmatically generating certain overlay features (one example being  L.circle with specific radius around all point features, *without* appending these to the data model to simply toggle this overlay on/off)
(5) programmatic generation of all possible points within a hand-drawn region, with certain interval using turf and exporting generated data set (with/without impacting data model)

While I understand these are  highly specific features and not likely needed for general usage, I'm interested to understand whether it is still possible somehow to port my old code against the new implementation, ie. is there a way to access (from Javascript) both map and data directly (other than just thru URL parameters)?

**Comment by chriswhong** [comment]
FYI `window.map` is already available, and I don't see why we can't also expose `window.data`.  We can also move these back into `window.api.map` and `window.api.data` which is how they used to be prior to the change.
