### ISSUE TITLE
Once you "move the globe" you cannot draw any features

### ISSUE THREAD

**Issue by JoshMcCullough** [mapbox/geojson.io#818]
On a fresh reload, I can immediately draw a feature. As soon as I rotate the view or zoom in/out, I can  no longer draw any features (nothing happens). Searching for an area allows you to draw a feature, but it seems only one?

**Comment by chriswhong** [comment]
Hi, thanks for opening this.  However, I am not able to reproduce the issue.  Can you share more about what you're trying, what browser and browser of version, etc?

> Searching for an area allows you to draw a feature

Searching places a marker on the map but does not draw anything.  I am able to draw features after search using Chrome 110.0.5481.100 on MacOS 12.6.2

**Comment by JoshMcCullough** [comment]
This seems to be working now. I was using Chrome but have closed/re-opened my browser since I posted this and now things are working okay. Sorry!
