### ISSUE TITLE
Print geojson lines according to WGS84

### ISSUE THREAD

**Issue by charlycou** [mapbox/geojson.io#821]
According to the [RFC](https://www.rfc-editor.org/rfc/rfc7946) 

> The coordinate reference system for all GeoJSON coordinates is a  geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84)

Thus, lines represented in geojson are not necessarily straight as they are currently printed in UI.  

> A line between two positions is a straight Cartesian line, the  shortest line between those two points in the coordinate reference  system

This can make huge differences especially for large lines/polygons

-------
This GeoJSON polygon
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [[[-55,  35 ],[58,35],[58,55], [-55,55],[-55, 35]]],
        "type": "Polygon"
      }
    }
  ]
} 
```
is printed in geojson.io shuch as: 
![Screenshot from 2023-02-20 14-32-53](https://user-images.githubusercontent.com/22495652/220122550-cc94dd44-f2a3-45f3-827d-c39d83f6b23b.png)
And should be printed such as:
![Screenshot from 2023-02-20 14-37-44](https://user-images.githubusercontent.com/22495652/220124326-654c90ac-77f1-4e77-9197-1315ef0f7389.png)

**Comment by chriswhong** [comment]
Thanks for your comments.  The rendering you see here is done by Mapbox GL JS, which is projecting the WGS84 coordinates into webmercator (EPSG 3857).  The globe view further transforms the webmercator tiles to create the globe effect, but the line drawn between two points is the shortest distance between them in the webmercator coordinate plane, not the shortest distance on the surface of the earth.

Closing as this isn't actionable in geojson.io
