### ISSUE TITLE
"Add simplestyle properties" broken

### ISSUE THREAD

**Issue by kuanb** [mapbox/geojson.io#823]
![image](https://user-images.githubusercontent.com/6053396/221670674-9420131d-a7fa-496b-ad74-9d84034c0d75.png)
See above image. In geojson popup - clicking the "Add simplestyle properties" errors. Expected behavior would be the addition of those parameters to the geojson style under properties.

![image](https://user-images.githubusercontent.com/6053396/221670807-c0b9ea82-8cdd-4cd2-8d87-0d87f3fe90c2.png)
Console captures the following error.

**Comment by marcbuettner** [comment]
same issue
