### ISSUE TITLE
Editing polygons broke after March 27th

### ISSUE THREAD

**Issue by georgique** [mapbox/geojson.io#831]
Steps to reproduce:
1. Create a polygon
2. Click "Edit geometries button" 
3. Try to drag one of the polygon's points

Expected behavior:
Point should be movable

Actual behavior:
Point doesn't move anywhere

Bug happens regardless of whether I have imported a polygon or added it manually.
Worked on March 27th, doesn't work on March 28th, so probably caused by some recent release.

Browser: MS Edge 111.0.1661.54 (Official build) (64-bit)
Console get these errors when I try to move the point:
![image](https://user-images.githubusercontent.com/15987211/228274144-5d93e5da-13e6-4c00-ab51-ca34d25ae9db.png)

**Comment by georgique** [comment]
Doesn't work in Firefox 111.0.1 (64-bit) either.
No missing resources in the Network tab.
Same issues in the console:
![image](https://user-images.githubusercontent.com/15987211/228274815-7c912aca-d191-421d-b14c-176431687919.png)

**Comment by georgique** [comment]
Seems it's caused by update of mapbox-gl-draw from 1.3.0 to 1.4.1 in #828
@chriswhong Please take a look

**Comment by chriswhong** [comment]
Thanks, we are working on the fix.

**Comment by SebitasPazos** [comment]
> Thanks, we are working on the fix.
Hello, this error appeared yesterday at 4 pm
