### ISSUE TITLE
How to add just functionalities to existing project?

### ISSUE THREAD

**Issue by SuedaSen** [mapbox/geojson.io#836]
Hi all,

I need just draw, open, save and meta parts of geojson.io. Is there any modular seperation packages for that job? For instance, for draw part using npm draw etc. Also I need them _Offline_ .  I mean, I just want to integrate these functionalities to my existing map project. Thanks in advance.

**Comment by chriswhong** [comment]
Hi, for drawing we use mapbox-gl-draw, which you can easily bring in to your own projects, though our implementation includes some custom modes. https://github.com/mapbox/mapbox-gl-draw

Everything else is baked in, but the source code is available so you can grab whatever you need.
