### ISSUE TITLE
Adding polygon point selection with the Rectangle Selection Tool

### ISSUE THREAD

**Issue by artegoser** [mapbox/geojson.io#841]
It would be very convenient to select polygon points in this way. Sometimes you need to select many points at once, and in this case it takes a very long time to select them separately.

**Comment by chriswhong** [comment]
Relevant thread, this would probably need to be added to `mapbox-gl-draw` and isn't something we are likely to add here https://github.com/mapbox/mapbox-gl-draw/issues/946
