### ISSUE TITLE
Workaround for Marker-Symbols? [Question]

### ISSUE THREAD

**Issue by Doctor-N0** [mapbox/geojson.io#843]
In my understanding, the `marker-symbol` property was removed (see [this](https://github.com/mapbox/geojson.io/pull/718) and [this](https://github.com/mapbox/geojson.io/issues/725) post), i.e. it is not any more possible to make e.g. a house symbol inside a marker:
```
      "type": "Feature",
      "properties": {
        "marker-color": "#0000ff", // different colors work
        "marker-size": "large", // different sized work
        "marker-symbol": "home", // this is not rendered anymore
      },
```
Therefore, I'd like to know if there's a workaround to create symbols (e.g. house) inside a marker?

**Comment by chriswhong** [comment]
<img width="891" alt="image" src="https://github.com/mapbox/geojson.io/assets/1833820/592a16b2-e566-441b-a606-d52bd9bc5853">

FYI using `marker-symbol` in a point feature's properties works again.
