### ISSUE TITLE
Invalid JSON file: Error: Invalid LngLat latitude value: must be between -90 and 90

### ISSUE THREAD

**Issue by claudinehellmuth** [mapbox/geojson.io#846]
I am using the tool as usual and i keep getting this error with the code when i try to open a file that made in geojson.io "Invalid JSON file: Error: Invalid LngLat latitude value: must be between -90 and 90"

i have never had this happen before and haven't been doing anything differently. I am creating the file in geojson.io and saving it out as a geoJSON file. then when i return to geojson.io to open the file i get this error message
thank you!

**Comment by chriswhong** [comment]
Can you share some geojson that triggers this error so we can reproduce it?

**Comment by chriswhong** [comment]
Most likely there was an invalid latitude in your file, if still think this is a bug and can provide more details, feel free to reopen
