### ISSUE TITLE
Presence of CRS element should not block display

### ISSUE THREAD

**Issue by stevage** [mapbox/geojson.io#849]
There are tools around, including GDAL's ogr2ogr (at least as recently as 3.0.4) which produce GeoJSON with this element at the top level

> "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },

geojson.io refuses to validate any file with this element, showing this error:

![image](https://github.com/mapbox/geojson.io/assets/678344/5d824706-2f32-46bd-bd9f-fb30ab1108a1)

That means you can't display the output of a GeoJSON file produced by GDAL. Even though the file is perfectly valid - it's simply a deprecated attribute that should be ignored.

**Comment by chriswhong** [comment]
This will need to be addressed in [geojsonhint](https://github.com/mapbox/geojsonhint).  A similar issue came up about enforcing winding order and the fix in https://github.com/mapbox/geojson.io/pull/786 was to accept as warnings anything returned by geojsonhint that does not have a `level` property.

The crs error does not have a `level` property so it's considered an error by geojson.io.  However you're allowed to add any arbitrary properties to the geojson that don't cause any error, so `crs` should still be allowed despite it not being required by the spec.

We look into getting this small change into geojsonhint.

**Comment by chriswhong** [comment]
Geojsonhint update: https://github.com/mapbox/geojsonhint/pull/91
