### ISSUE TITLE
Wrong street name

### ISSUE THREAD

**Issue by leifskaar** [mapbox/geojson.io#850]
There is a wrong street name in your map from Western Norway. The street is called "Høgatun" but in your map it is called "Vestlivegen". This creates problems for our customers when we refer to "Høgatun" and the map says "Vestlivegen". Vestlivegen is a street in the same area but a few hundred meters away. Please see the screen dump from google maps for the correct name.
![geojson](https://github.com/mapbox/geojson.io/assets/41043171/3cfca1b7-3ed1-4cc8-804b-a8b47bab4f9a)
![google maps](https://github.com/mapbox/geojson.io/assets/41043171/e1e31a34-fa7e-4c6d-91d6-503f13848ee3)

**Comment by chriswhong** [comment]
Hi, please submit this correction at https://www.mapbox.com/contribute/#/.  The Mapbox data team will get it sorted out.
