### ISSUE TITLE
shape file coordinates mismatch

### ISSUE THREAD

**Issue by etnad1977** [mapbox/geojson.io#858]
Sorry for this probably silly question. I am a totally beginner.

Why do i get a mismatch in the shape file coordinates I download from geojson.io tool and the coordinates on the right column?
Am I misinterpreting the tool?

If i load the shape file in GE, it goes in place, whereas the coordinate list brings me miles away.

Thanks a lot

**Comment by chriswhong** [comment]
> whereas the coordinate list brings me miles away.

What does this mean?  Where/how are you using a coordinate list, and what is bringing you miles away?  My suspicion is that you're reversing latitude and longitude in whatever you're testing these coordinates in.  

Closing as we can assume this is not an issue with geojson.io.  Happy to help you figure this out if you can provide more context.
