### ISSUE TITLE
issue with co-ordinates

### ISSUE THREAD

**Issue by satyasandhya** [mapbox/geojson.io#876]
Hello,
I have a Geo JSON 
i.e
[map.json](https://github.com/mapbox/geojson.io/files/14111856/map.json)
but when i use the JSON it's returning error showing outer range should be 90 to -90
i tried it to open in the map edit page but it's not working.

Thanks & Regards...

**Comment by chriswhong** [comment]
The file you attached does not contain valid geojson.
