### ISSUE TITLE
API question: Can a GeoJson file be loaded from a local drive?

### ISSUE THREAD

**Issue by DaveF63** [mapbox/geojson.io#892]
Can a GeoJson file be loaded from a local drive using the API?

I can see various options for loading via a URL parameter, but not a file.
Am I missing something?

**Comment by chriswhong** [comment]
You can click "Open" in the menu bar and choose a geojson file, or drag and drop the geojson file, or paste the geojson text into the text editor.

**Comment by DaveF63** [comment]
My Question was about the API. Unsure why the Q. was closed.
